/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: outputs/contracts/openapi.snapshot.json
 * Snapshot SHA256: 25b8a8b16d8d391fa6a7a63add4ea7f68aab4d9b888d3c432ea6cde5f58fdf3c
 * Generated at: 2026-02-10T22:10:47.102Z
 *
 * To regenerate: npm run gen:api
 */

import * as http from '@platform/http'

export const brainosServiceGen: any = {
  /** Brain Blind Spots */
  async brainBlindSpotsApiBrainBlindSpotsGet(_params?: any): Promise<any> {
    return http.get('/api/brain/blind-spots', _params ? { params: _params } : undefined)
  },

  /** Brain Build */
  async brainBuildApiBrainBuildPost(data?: any): Promise<any> {
    return http.post('/api/brain/build', data)
  },

  /** Brain Coverage */
  async brainCoverageApiBrainCoverageGet(_params?: any): Promise<any> {
    return http.get('/api/brain/coverage', _params ? { params: _params } : undefined)
  },

  /** Brain Dashboard */
  async brainDashboardApiBrainDashboardGet(_params?: any): Promise<any> {
    return http.get('/api/brain/dashboard', _params ? { params: _params } : undefined)
  },

  /** Replay Brain Governance Decision */
  async replayBrainGovernanceDecisionApiBrainGovernanceDecisionsDecisionIdReplayGet(decision_id: any, _params?: any): Promise<any> {
    return http.get(`/api/brain/governance/decisions/${decision_id}/replay`, _params ? { params: _params } : undefined)
  },

  /** Signoff Brain Governance Decision */
  async signoffBrainGovernanceDecisionApiBrainGovernanceDecisionsDecisionIdSignoffPost(decision_id: any, data?: any): Promise<any> {
    return http.post(`/api/brain/governance/decisions/${decision_id}/signoff`, data)
  },

  /** Get Brain Governance Decision */
  async getBrainGovernanceDecisionApiBrainGovernanceDecisionsDecisionIdGet(decision_id: any, _params?: any): Promise<any> {
    return http.get(`/api/brain/governance/decisions/${decision_id}`, _params ? { params: _params } : undefined)
  },

  /** List Brain Governance Decisions */
  async listBrainGovernanceDecisionsApiBrainGovernanceDecisionsGet(_params?: any): Promise<any> {
    return http.get('/api/brain/governance/decisions', _params ? { params: _params } : undefined)
  },

  /** Brain Knowledge Health */
  async brainKnowledgeHealthApiBrainKnowledgeHealthGet(_params?: any): Promise<any> {
    return http.get('/api/brain/knowledge-health', _params ? { params: _params } : undefined)
  },

  /** Brain Stats */
  async brainStatsApiBrainStatsGet(_params?: any): Promise<any> {
    return http.get('/api/brain/stats', _params ? { params: _params } : undefined)
  },

  /** Brain Subgraph */
  async brainSubgraphApiBrainSubgraphGet(_params?: any): Promise<any> {
    return http.get('/api/brain/subgraph', _params ? { params: _params } : undefined)
  },

  /** Context Attach */
  async contextAttachApiContextAttachPost(data?: any): Promise<any> {
    return http.post('/api/context/attach', data)
  },

  /** Context Detach */
  async contextDetachApiContextDetachPost(data?: any): Promise<any> {
    return http.post('/api/context/detach', data)
  },

  /** Context Refresh */
  async contextRefreshApiContextRefreshPost(data?: any): Promise<any> {
    return http.post('/api/context/refresh', data)
  },

  /** Get Context Status */
  async getContextStatusApiContextStatusGet(_params?: any): Promise<any> {
    return http.get('/api/context/status', _params ? { params: _params } : undefined)
  },

  /** Info Need Metrics Summary */
  async infoNeedMetricsSummaryApiInfoNeedMetricsSummaryGet(_params?: any): Promise<any> {
    return http.get('/api/info-need-metrics/summary', _params ? { params: _params } : undefined)
  },

  /** List Knowledge Jobs */
  async listKnowledgeJobsApiKnowledgeJobsGet(_params?: any): Promise<any> {
    return http.get('/api/knowledge/jobs', _params ? { params: _params } : undefined)
  },

  /** Create Job */
  async createJobApiKnowledgeJobsPost(data?: any): Promise<any> {
    return http.post('/api/knowledge/jobs', data)
  },

  /** Sync Source */
  async syncSourceApiKnowledgeSourcesSourceIdSyncPost(source_id: any, data?: any): Promise<any> {
    return http.post(`/api/knowledge/sources/${source_id}/sync`, data)
  },

  /** Sync All Sources */
  async syncAllSourcesApiKnowledgeSourcesSyncAllPost(data?: any): Promise<any> {
    return http.post('/api/knowledge/sources/sync-all', data)
  },

  /** List Knowledge Sources */
  async listKnowledgeSourcesApiKnowledgeSourcesGet(_params?: any): Promise<any> {
    return http.get('/api/knowledge/sources', _params ? { params: _params } : undefined)
  },

  /** Create Knowledge Source */
  async createKnowledgeSourceApiKnowledgeSourcesPost(data?: any): Promise<any> {
    return http.post('/api/knowledge/sources', data)
  },

  /** Approve Review Queue */
  async approveReviewQueueApiV3ReviewQueueItemIdApprovePost(item_id: any, data?: any): Promise<any> {
    return http.post(`/api/v3/review-queue/${item_id}/approve`, data)
  },

  /** Reject Review Queue */
  async rejectReviewQueueApiV3ReviewQueueItemIdRejectPost(item_id: any, data?: any): Promise<any> {
    return http.post(`/api/v3/review-queue/${item_id}/reject`, data)
  },

  /** Get Review Queue Item */
  async getReviewQueueItemApiV3ReviewQueueItemIdGet(item_id: any, _params?: any): Promise<any> {
    return http.get(`/api/v3/review-queue/${item_id}`, _params ? { params: _params } : undefined)
  },

  /** List Review Queue */
  async listReviewQueueApiV3ReviewQueueGet(_params?: any): Promise<any> {
    return http.get('/api/v3/review-queue', _params ? { params: _params } : undefined)
  }
}

export type brainosServiceGenApi = typeof brainosServiceGen
