/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: outputs/contracts/openapi.snapshot.json
 * Snapshot SHA256: 25b8a8b16d8d391fa6a7a63add4ea7f68aab4d9b888d3c432ea6cde5f58fdf3c
 * Generated at: 2026-02-10T22:10:47.104Z
 *
 * To regenerate: npm run gen:api
 */

import * as http from '@platform/http'

export const communicationosServiceGen: any = {
  /** List Channels Marketplace */
  async listChannelsMarketplaceApiChannelsMarketplaceGet(_params?: any): Promise<any> {
    return http.get('/api/channels-marketplace', _params ? { params: _params } : undefined)
  },

  /** Switch Binding */
  async switchBindingApiChannelsChannelIdBindingsBindingIdSwitchPost(channel_id: any, binding_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/bindings/${binding_id}/switch`, data)
  },

  /** List Bindings */
  async listBindingsApiChannelsChannelIdBindingsGet(channel_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/${channel_id}/bindings`, _params ? { params: _params } : undefined)
  },

  /** Get Channel Config */
  async getChannelConfigApiChannelsChannelIdConfigGet(channel_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/${channel_id}/config`, _params ? { params: _params } : undefined)
  },

  /** Configure Channel */
  async configureChannelApiChannelsChannelIdConfigurePost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/configure`, data)
  },

  /** Connect Channel */
  async connectChannelApiChannelsChannelIdConnectPost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/connect`, data)
  },

  /** Disable Channel */
  async disableChannelApiChannelsChannelIdDisablePost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/disable`, data)
  },

  /** Enable Channel */
  async enableChannelApiChannelsChannelIdEnablePost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/enable`, data)
  },

  /** Channel Qr */
  async channelQrApiChannelsChannelIdQrGet(channel_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/${channel_id}/qr`, _params ? { params: _params } : undefined)
  },

  /** Send Message Tool */
  async sendMessageToolApiChannelsChannelIdSendPost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/send`, data)
  },

  /** Channel Status */
  async channelStatusApiChannelsChannelIdStatusGet(channel_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/${channel_id}/status`, _params ? { params: _params } : undefined)
  },

  /** Draft Reply */
  async draftReplyApiChannelsEmailInstanceIdDraftReplyPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/draft-reply`, data)
  },

  /** Mark Read */
  async markReadApiChannelsEmailInstanceIdMarkReadPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/mark-read`, data)
  },

  /** Get Message */
  async getMessageApiChannelsEmailInstanceIdMessageMessageIdGet(instance_id: any, message_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/email/${instance_id}/message/${message_id}`, _params ? { params: _params } : undefined)
  },

  /** Oauth Disconnect */
  async oauthDisconnectApiChannelsEmailInstanceIdOauthDisconnectPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/oauth/disconnect`, data)
  },

  /** Oauth Start */
  async oauthStartApiChannelsEmailInstanceIdOauthStartGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/email/${instance_id}/oauth/start`, _params ? { params: _params } : undefined)
  },

  /** Oauth Status */
  async oauthStatusApiChannelsEmailInstanceIdOauthStatusGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/email/${instance_id}/oauth/status`, _params ? { params: _params } : undefined)
  },

  /** Send Draft */
  async sendDraftApiChannelsEmailInstanceIdSendPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/send`, data)
  },

  /** Snooze Message */
  async snoozeMessageApiChannelsEmailInstanceIdSnoozePost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/snooze`, data)
  },

  /** List Unread */
  async listUnreadApiChannelsEmailInstanceIdUnreadGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/email/${instance_id}/unread`, _params ? { params: _params } : undefined)
  },

  /** Allow Sender */
  async allowSenderApiChannelsEmailInstancesInstanceIdRulesAllowSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/allow_sender`, data)
  },

  /** Block Domain */
  async blockDomainApiChannelsEmailInstancesInstanceIdRulesBlockDomainPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/block_domain`, data)
  },

  /** Block Sender */
  async blockSenderApiChannelsEmailInstancesInstanceIdRulesBlockSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/block_sender`, data)
  },

  /** Unblock Domain */
  async unblockDomainApiChannelsEmailInstancesInstanceIdRulesUnblockDomainPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/unblock_domain`, data)
  },

  /** Unblock Sender */
  async unblockSenderApiChannelsEmailInstancesInstanceIdRulesUnblockSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/unblock_sender`, data)
  },

  /** Test Instance */
  async testInstanceApiChannelsEmailInstancesInstanceIdTestPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/test`, data)
  },

  /** List Instances */
  async listInstancesApiChannelsEmailInstancesGet(_params?: any): Promise<any> {
    return http.get('/api/channels/email/instances', _params ? { params: _params } : undefined)
  },

  /** Create Instance */
  async createInstanceApiChannelsEmailInstancesPost(data?: any): Promise<any> {
    return http.post('/api/channels/email/instances', data)
  },

  /** Oauth Callback */
  async oauthCallbackApiChannelsEmailOauthCallbackGet(_params?: any): Promise<any> {
    return http.get('/api/channels/email/oauth/callback', _params ? { params: _params } : undefined)
  },

  /** List Configured Channels */
  async listConfiguredChannelsApiChannelsGet(_params?: any): Promise<any> {
    return http.get('/api/channels', _params ? { params: _params } : undefined)
  },

  /** List Comm Audits */
  async listCommAuditsApiCommunicationAuditsGet(_params?: any): Promise<any> {
    return http.get('/api/communication/audits', _params ? { params: _params } : undefined)
  },

  /** Get Comm Mode */
  async getCommModeApiCommunicationModeGet(_params?: any): Promise<any> {
    return http.get('/api/communication/mode', _params ? { params: _params } : undefined)
  },

  /** Set Comm Mode */
  async setCommModeApiCommunicationModePut(data?: any): Promise<any> {
    return http.put('/api/communication/mode', data)
  },

  /** Get Comm Policy */
  async getCommPolicyApiCommunicationPolicyGet(_params?: any): Promise<any> {
    return http.get('/api/communication/policy', _params ? { params: _params } : undefined)
  },

  /** Get Comm Status */
  async getCommStatusApiCommunicationStatusGet(_params?: any): Promise<any> {
    return http.get('/api/communication/status', _params ? { params: _params } : undefined)
  },

  /** Uninstall MCP package (Deprecated Alias) */
  async uninstallMcpPackageAliasApiCommunicationosMcpPackagesPackageIdUninstallDelete(package_id: any): Promise<any> {
    return http.del(`/api/communicationos/mcp/packages/${package_id}/uninstall`)
  },

  /** List Local Aws Profiles */
  async listLocalAwsProfilesApiMcpAwsProfilesGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/aws/profiles', _params ? { params: _params } : undefined)
  },

  /** Draft Reply */
  async draftReplyApiMcpEmailInstanceIdDraftReplyPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/draft-reply`, data)
  },

  /** Mark Read */
  async markReadApiMcpEmailInstanceIdMarkReadPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/mark-read`, data)
  },

  /** Get Message */
  async getMessageApiMcpEmailInstanceIdMessageMessageIdGet(instance_id: any, message_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/email/${instance_id}/message/${message_id}`, _params ? { params: _params } : undefined)
  },

  /** Oauth Disconnect */
  async oauthDisconnectApiMcpEmailInstanceIdOauthDisconnectPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/oauth/disconnect`, data)
  },

  /** Oauth Start */
  async oauthStartApiMcpEmailInstanceIdOauthStartGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/email/${instance_id}/oauth/start`, _params ? { params: _params } : undefined)
  },

  /** Oauth Status */
  async oauthStatusApiMcpEmailInstanceIdOauthStatusGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/email/${instance_id}/oauth/status`, _params ? { params: _params } : undefined)
  },

  /** Send Draft */
  async sendDraftApiMcpEmailInstanceIdSendPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/send`, data)
  },

  /** Snooze Message */
  async snoozeMessageApiMcpEmailInstanceIdSnoozePost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/snooze`, data)
  },

  /** List Unread */
  async listUnreadApiMcpEmailInstanceIdUnreadGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/email/${instance_id}/unread`, _params ? { params: _params } : undefined)
  },

  /** Allow Sender */
  async allowSenderApiMcpEmailInstancesInstanceIdRulesAllowSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/allow_sender`, data)
  },

  /** Block Domain */
  async blockDomainApiMcpEmailInstancesInstanceIdRulesBlockDomainPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/block_domain`, data)
  },

  /** Block Sender */
  async blockSenderApiMcpEmailInstancesInstanceIdRulesBlockSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/block_sender`, data)
  },

  /** Unblock Domain */
  async unblockDomainApiMcpEmailInstancesInstanceIdRulesUnblockDomainPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/unblock_domain`, data)
  },

  /** Unblock Sender */
  async unblockSenderApiMcpEmailInstancesInstanceIdRulesUnblockSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/unblock_sender`, data)
  },

  /** Test Email Instance */
  async testEmailInstanceApiMcpEmailInstancesInstanceIdTestPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/test`, data)
  },

  /** List Email Instances */
  async listEmailInstancesApiMcpEmailInstancesGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/email/instances', _params ? { params: _params } : undefined)
  },

  /** Create Email Instance */
  async createEmailInstanceApiMcpEmailInstancesPost(data?: any): Promise<any> {
    return http.post('/api/mcp/email/instances', data)
  },

  /** Oauth Callback */
  async oauthCallbackApiMcpEmailOauthCallbackGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/email/oauth/callback', _params ? { params: _params } : undefined)
  },

  /** Attach Mcp Package */
  async attachMcpPackageApiMcpMarketplaceAttachPost(data?: any): Promise<any> {
    return http.post('/api/mcp/marketplace/attach', data)
  },

  /** Get Mcp Catalog */
  async getMcpCatalogApiMcpMarketplaceCatalogGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/marketplace/catalog', _params ? { params: _params } : undefined)
  },

  /** Get Mcp Preview */
  async getMcpPreviewApiMcpMarketplaceGovernancePreviewPackageIdGet(package_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/marketplace/governance-preview/${package_id}`, _params ? { params: _params } : undefined)
  },

  /** Uninstall Mcp Package Canonical */
  async uninstallMcpPackageCanonicalApiMcpMarketplacePackagesPackageIdDelete(package_id: any): Promise<any> {
    return http.del(`/api/mcp/marketplace/packages/${package_id}`)
  },

  /** Get Mcp Package */
  async getMcpPackageApiMcpMarketplacePackagesPackageIdGet(package_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/marketplace/packages/${package_id}`, _params ? { params: _params } : undefined)
  },

  /** List Mcp Packages */
  async listMcpPackagesApiMcpMarketplacePackagesGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/marketplace/packages', _params ? { params: _params } : undefined)
  },

  /** Configure Mcp Server */
  async configureMcpServerApiMcpServersServerIdConfigPost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/config`, data)
  },

  /** Connect Mcp Server */
  async connectMcpServerApiMcpServersServerIdConnectPost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/connect`, data)
  },

  /** Disable Mcp Server */
  async disableMcpServerApiMcpServersServerIdDisablePost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/disable`, data)
  },

  /** Disconnect Mcp Server */
  async disconnectMcpServerApiMcpServersServerIdDisconnectPost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/disconnect`, data)
  },

  /** Enable Mcp Server */
  async enableMcpServerApiMcpServersServerIdEnablePost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/enable`, data)
  },

  /** Preflight Mcp Server */
  async preflightMcpServerApiMcpServersServerIdPreflightGet(server_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/servers/${server_id}/preflight`, _params ? { params: _params } : undefined)
  },

  /** Get Mcp Server */
  async getMcpServerApiMcpServersServerIdGet(server_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/servers/${server_id}`, _params ? { params: _params } : undefined)
  },

  /** Refresh Mcp Servers */
  async refreshMcpServersApiMcpServersRefreshPost(data?: any): Promise<any> {
    return http.post('/api/mcp/servers/refresh', data)
  },

  /** List Mcp Servers */
  async listMcpServersApiMcpServersGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/servers', _params ? { params: _params } : undefined)
  },

  /** Delete Voice Contact */
  async deleteVoiceContactApiVoiceContactsContactIdDelete(contact_id: any): Promise<any> {
    return http.del(`/api/voice-contacts/${contact_id}`)
  },

  /** Update Voice Contact */
  async updateVoiceContactApiVoiceContactsContactIdPut(contact_id: any, data?: any): Promise<any> {
    return http.put(`/api/voice-contacts/${contact_id}`, data)
  },

  /** List Voice Contacts */
  async listVoiceContactsApiVoiceContactsGet(_params?: any): Promise<any> {
    return http.get('/api/voice-contacts', _params ? { params: _params } : undefined)
  },

  /** Create Voice Contact */
  async createVoiceContactApiVoiceContactsPost(data?: any): Promise<any> {
    return http.post('/api/voice-contacts', data)
  },

  /** Health */
  async healthApiVoiceHealthGet(_params?: any): Promise<any> {
    return http.get('/api/voice/health', _params ? { params: _params } : undefined)
  },

  /** Inbound */
  async inboundApiVoiceTwilioInboundPost(data?: any): Promise<any> {
    return http.post('/api/voice/twilio/inbound', data)
  }
}

export type communicationosServiceGenApi = typeof communicationosServiceGen
