/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: outputs/contracts/openapi.snapshot.json
 * Snapshot SHA256: 25b8a8b16d8d391fa6a7a63add4ea7f68aab4d9b888d3c432ea6cde5f58fdf3c
 * Generated at: 2026-02-10T22:10:47.102Z
 *
 * To regenerate: npm run gen:api
 */

import * as http from '@platform/http'

export const memoryosServiceGen: any = {
  /** Memory Entries */
  async memoryEntriesApiMemoryEntriesGet(_params?: any): Promise<any> {
    return http.get('/api/memory/entries', _params ? { params: _params } : undefined)
  },

  /** Approve Proposal */
  async approveProposalApiMemoryProposalsProposalIdApprovePost(proposal_id: any, data?: any): Promise<any> {
    return http.post(`/api/memory/proposals/${proposal_id}/approve`, data)
  },

  /** Reject Proposal */
  async rejectProposalApiMemoryProposalsProposalIdRejectPost(proposal_id: any, data?: any): Promise<any> {
    return http.post(`/api/memory/proposals/${proposal_id}/reject`, data)
  },

  /** Get Proposal */
  async getProposalApiMemoryProposalsProposalIdGet(proposal_id: any, _params?: any): Promise<any> {
    return http.get(`/api/memory/proposals/${proposal_id}`, _params ? { params: _params } : undefined)
  },

  /** Proposal Stats */
  async proposalStatsApiMemoryProposalsStatsGet(_params?: any): Promise<any> {
    return http.get('/api/memory/proposals/stats', _params ? { params: _params } : undefined)
  },

  /** List Proposals */
  async listProposalsApiMemoryProposalsGet(_params?: any): Promise<any> {
    return http.get('/api/memory/proposals', _params ? { params: _params } : undefined)
  },

  /** Propose Memory */
  async proposeMemoryApiMemoryProposePost(data?: any): Promise<any> {
    return http.post('/api/memory/propose', data)
  }
}

export type memoryosServiceGenApi = typeof memoryosServiceGen
