/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: outputs/contracts/openapi.snapshot.json
 * Snapshot SHA256: 25b8a8b16d8d391fa6a7a63add4ea7f68aab4d9b888d3c432ea6cde5f58fdf3c
 * Generated at: 2026-02-10T22:10:47.103Z
 *
 * To regenerate: npm run gen:api
 */

import * as http from '@platform/http'

export const networkosServiceGen: any = {
  /** Capability Dashboard Stats */
  async capabilityDashboardStatsApiCapabilityDashboardStatsGet(_params?: any): Promise<any> {
    return http.get('/api/capability/dashboard/stats', _params ? { params: _params } : undefined)
  },

  /** Capability Governance Audit */
  async capabilityGovernanceAuditApiCapabilityGovernanceAuditGet(_params?: any): Promise<any> {
    return http.get('/api/capability/governance/audit', _params ? { params: _params } : undefined)
  },

  /** Delete Execution Policy */
  async deleteExecutionPolicyApiExecutionPoliciesPolicyIdDelete(policy_id: any): Promise<any> {
    return http.del(`/api/execution/policies/${policy_id}`)
  },

  /** Update Execution Policy */
  async updateExecutionPolicyApiExecutionPoliciesPolicyIdPut(policy_id: any, data?: any): Promise<any> {
    return http.put(`/api/execution/policies/${policy_id}`, data)
  },

  /** List Execution Policies */
  async listExecutionPoliciesApiExecutionPoliciesGet(_params?: any): Promise<any> {
    return http.get('/api/execution/policies', _params ? { params: _params } : undefined)
  },

  /** Create Execution Policy */
  async createExecutionPolicyApiExecutionPoliciesPost(data?: any): Promise<any> {
    return http.post('/api/execution/policies', data)
  },

  /** Connect Federation Node */
  async connectFederationNodeApiFederationNodesNodeIdConnectPost(node_id: any, data?: any): Promise<any> {
    return http.post(`/api/federation/nodes/${node_id}/connect`, data)
  },

  /** Disconnect Federation Node */
  async disconnectFederationNodeApiFederationNodesNodeIdDisconnectPost(node_id: any, data?: any): Promise<any> {
    return http.post(`/api/federation/nodes/${node_id}/disconnect`, data)
  },

  /** List Federation Nodes */
  async listFederationNodesApiFederationNodesGet(_params?: any): Promise<any> {
    return http.get('/api/federation/nodes', _params ? { params: _params } : undefined)
  },

  /** Get Evolution Decision */
  async getEvolutionDecisionApiGovernanceEvolutionDecisionsDecisionIdGet(decision_id: any, _params?: any): Promise<any> {
    return http.get(`/api/governance/evolution-decisions/${decision_id}`, _params ? { params: _params } : undefined)
  },

  /** List Evolution Decisions */
  async listEvolutionDecisionsApiGovernanceEvolutionDecisionsGet(_params?: any): Promise<any> {
    return http.get('/api/governance/evolution-decisions', _params ? { params: _params } : undefined)
  },

  /** Delete Governance Finding */
  async deleteGovernanceFindingApiGovernanceFindingsFindingIdDelete(finding_id: any): Promise<any> {
    return http.del(`/api/governance/findings/${finding_id}`)
  },

  /** Get Governance Finding */
  async getGovernanceFindingApiGovernanceFindingsFindingIdGet(finding_id: any, _params?: any): Promise<any> {
    return http.get(`/api/governance/findings/${finding_id}`, _params ? { params: _params } : undefined)
  },

  /** List Governance Findings */
  async listGovernanceFindingsApiGovernanceFindingsGet(_params?: any): Promise<any> {
    return http.get('/api/governance/findings', _params ? { params: _params } : undefined)
  },

  /** List Trust Tiers */
  async listTrustTiersApiGovernanceTrustTiersGet(_params?: any): Promise<any> {
    return http.get('/api/governance/trust-tiers', _params ? { params: _params } : undefined)
  },

  /** Patch Lead Finding Status */
  async patchLeadFindingStatusApiLeadFindingsFindingIdStatusPatch(finding_id: any, data?: any): Promise<any> {
    return http.patch(`/api/lead/findings/${finding_id}/status`, data)
  },

  /** List Lead Findings */
  async listLeadFindingsApiLeadFindingsGet(_params?: any): Promise<any> {
    return http.get('/api/lead/findings', _params ? { params: _params } : undefined)
  },

  /** List Lead Scans */
  async listLeadScansApiLeadScansGet(_params?: any): Promise<any> {
    return http.get('/api/lead/scans', _params ? { params: _params } : undefined)
  },

  /** Approve Marketplace Capability */
  async approveMarketplaceCapabilityApiMarketplaceCapabilitiesCapabilityIdApprovePost(capability_id: any, data?: any): Promise<any> {
    return http.post(`/api/marketplace/capabilities/${capability_id}/approve`, data)
  },

  /** Reject Marketplace Capability */
  async rejectMarketplaceCapabilityApiMarketplaceCapabilitiesCapabilityIdRejectPost(capability_id: any, data?: any): Promise<any> {
    return http.post(`/api/marketplace/capabilities/${capability_id}/reject`, data)
  },

  /** Get Marketplace Capability */
  async getMarketplaceCapabilityApiMarketplaceCapabilitiesCapabilityIdGet(capability_id: any, _params?: any): Promise<any> {
    return http.get(`/api/marketplace/capabilities/${capability_id}`, _params ? { params: _params } : undefined)
  },

  /** List Marketplace Capabilities */
  async listMarketplaceCapabilitiesApiMarketplaceCapabilitiesGet(_params?: any): Promise<any> {
    return http.get('/api/marketplace/capabilities', _params ? { params: _params } : undefined)
  },

  /** Patch Publisher Trust */
  async patchPublisherTrustApiMarketplacePublishersPublisherIdTrustPatch(publisher_id: any, data?: any): Promise<any> {
    return http.patch(`/api/marketplace/publishers/${publisher_id}/trust`, data)
  },

  /** Get Publisher */
  async getPublisherApiMarketplacePublishersPublisherIdGet(publisher_id: any, _params?: any): Promise<any> {
    return http.get(`/api/marketplace/publishers/${publisher_id}`, _params ? { params: _params } : undefined)
  },

  /** List Publishers */
  async listPublishersApiMarketplacePublishersGet(_params?: any): Promise<any> {
    return http.get('/api/marketplace/publishers', _params ? { params: _params } : undefined)
  },

  /** Trust Trajectory */
  async trustTrajectoryApiTrustTrajectorySubjectIdGet(subject_id: any, _params?: any): Promise<any> {
    return http.get(`/api/trust/trajectory/${subject_id}`, _params ? { params: _params } : undefined)
  }
}

export type networkosServiceGenApi = typeof networkosServiceGen
