/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: outputs/contracts/openapi.snapshot.json
 * Snapshot SHA256: 25b8a8b16d8d391fa6a7a63add4ea7f68aab4d9b888d3c432ea6cde5f58fdf3c
 * Generated at: 2026-02-10T22:10:47.099Z
 *
 * To regenerate: npm run gen:api
 */

import * as http from '@platform/http'

export const octopusosServiceGen: any = {
  /** Archive Project */
  async archiveProjectApiProjectsProjectIdArchivePost(project_id: any, data?: any): Promise<any> {
    return http.post(`/api/projects/${project_id}/archive`, data)
  },

  /** Delete Repo */
  async deleteRepoApiProjectsProjectIdReposRepoIdDelete(project_id: any, repo_id: any): Promise<any> {
    return http.del(`/api/projects/${project_id}/repos/${repo_id}`)
  },

  /** Get Repo */
  async getRepoApiProjectsProjectIdReposRepoIdGet(project_id: any, repo_id: any, _params?: any): Promise<any> {
    return http.get(`/api/projects/${project_id}/repos/${repo_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Repo */
  async updateRepoApiProjectsProjectIdReposRepoIdPut(project_id: any, repo_id: any, data?: any): Promise<any> {
    return http.put(`/api/projects/${project_id}/repos/${repo_id}`, data)
  },

  /** List Repos */
  async listReposApiProjectsProjectIdReposGet(project_id: any, _params?: any): Promise<any> {
    return http.get(`/api/projects/${project_id}/repos`, _params ? { params: _params } : undefined)
  },

  /** Add Repo */
  async addRepoApiProjectsProjectIdReposPost(project_id: any, data?: any): Promise<any> {
    return http.post(`/api/projects/${project_id}/repos`, data)
  },

  /** Delete Project */
  async deleteProjectApiProjectsProjectIdDelete(project_id: any): Promise<any> {
    return http.del(`/api/projects/${project_id}`)
  },

  /** Get Project Detail */
  async getProjectDetailApiProjectsProjectIdGet(project_id: any, _params?: any): Promise<any> {
    return http.get(`/api/projects/${project_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Project */
  async updateProjectApiProjectsProjectIdPatch(project_id: any, data?: any): Promise<any> {
    return http.patch(`/api/projects/${project_id}`, data)
  },

  /** List Projects */
  async listProjectsApiProjectsGet(_params?: any): Promise<any> {
    return http.get('/api/projects', _params ? { params: _params } : undefined)
  },

  /** Create Project */
  async createProjectApiProjectsPost(data?: any): Promise<any> {
    return http.post('/api/projects', data)
  },

  /** Delete Repo */
  async deleteRepoApiReposRepoIdDelete(repo_id: any): Promise<any> {
    return http.del(`/api/repos/${repo_id}`)
  },

  /** Get Repo */
  async getRepoApiReposRepoIdGet(repo_id: any, _params?: any): Promise<any> {
    return http.get(`/api/repos/${repo_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Repo */
  async updateRepoApiReposRepoIdPatch(repo_id: any, data?: any): Promise<any> {
    return http.patch(`/api/repos/${repo_id}`, data)
  },

  /** List Repos */
  async listReposApiReposGet(_params?: any): Promise<any> {
    return http.get('/api/repos', _params ? { params: _params } : undefined)
  },

  /** Create Repo */
  async createRepoApiReposPost(data?: any): Promise<any> {
    return http.post('/api/repos', data)
  },

  /** Get Task Route */
  async getTaskRouteApiTasksTaskIdRouteGet(task_id: any, _params?: any): Promise<any> {
    return http.get(`/api/tasks/${task_id}/route`, _params ? { params: _params } : undefined)
  },

  /** Update Task Route */
  async updateTaskRouteApiTasksTaskIdRoutePost(task_id: any, data?: any): Promise<any> {
    return http.post(`/api/tasks/${task_id}/route`, data)
  },

  /** Delete Task */
  async deleteTaskApiTasksTaskIdDelete(task_id: any): Promise<any> {
    return http.del(`/api/tasks/${task_id}`)
  },

  /** Get Task */
  async getTaskApiTasksTaskIdGet(task_id: any, _params?: any): Promise<any> {
    return http.get(`/api/tasks/${task_id}`, _params ? { params: _params } : undefined)
  },

  /** Batch Create Tasks */
  async batchCreateTasksApiTasksBatchPost(data?: any): Promise<any> {
    return http.post('/api/tasks/batch', data)
  },

  /** Create And Start Task */
  async createAndStartTaskApiTasksCreateAndStartPost(data?: any): Promise<any> {
    return http.post('/api/tasks/create_and_start', data)
  },

  /** Cancel Exec Task */
  async cancelExecTaskApiTasksItemsTaskIdCancelPost(task_id: any, data?: any): Promise<any> {
    return http.post(`/api/tasks/items/${task_id}/cancel`, data)
  },

  /** Retry Exec Task */
  async retryExecTaskApiTasksItemsTaskIdRetryPost(task_id: any, data?: any): Promise<any> {
    return http.post(`/api/tasks/items/${task_id}/retry`, data)
  },

  /** Get Exec Task */
  async getExecTaskApiTasksItemsTaskIdGet(task_id: any, _params?: any): Promise<any> {
    return http.get(`/api/tasks/items/${task_id}`, _params ? { params: _params } : undefined)
  },

  /** List Exec Tasks */
  async listExecTasksApiTasksItemsGet(_params?: any): Promise<any> {
    return http.get('/api/tasks/items', _params ? { params: _params } : undefined)
  },

  /** List Tasks */
  async listTasksApiTasksGet(_params?: any): Promise<any> {
    return http.get('/api/tasks', _params ? { params: _params } : undefined)
  },

  /** Create Task */
  async createTaskApiTasksPost(data?: any): Promise<any> {
    return http.post('/api/tasks', data)
  },

  /** List Project Repos */
  async listProjectReposApiV031ProjectsProjectIdReposGet(project_id: any, _params?: any): Promise<any> {
    return http.get(`/api/v0.31/projects/${project_id}/repos`, _params ? { params: _params } : undefined)
  },

  /** Create Project Repo */
  async createProjectRepoApiV031ProjectsProjectIdReposPost(project_id: any, data?: any): Promise<any> {
    return http.post(`/api/v0.31/projects/${project_id}/repos`, data)
  },

  /** Get Project */
  async getProjectApiV031ProjectsProjectIdGet(project_id: any, _params?: any): Promise<any> {
    return http.get(`/api/v0.31/projects/${project_id}`, _params ? { params: _params } : undefined)
  },

  /** List Projects */
  async listProjectsApiV031ProjectsGet(_params?: any): Promise<any> {
    return http.get('/api/v0.31/projects', _params ? { params: _params } : undefined)
  },

  /** Create Project */
  async createProjectApiV031ProjectsPost(data?: any): Promise<any> {
    return http.post('/api/v0.31/projects', data)
  },

  /** List Tasks */
  async listTasksApiV031TasksGet(_params?: any): Promise<any> {
    return http.get('/api/v0.31/tasks', _params ? { params: _params } : undefined)
  },

  /** Create Task */
  async createTaskApiV031TasksPost(data?: any): Promise<any> {
    return http.post('/api/v0.31/tasks', data)
  }
}

export type octopusosServiceGenApi = typeof octopusosServiceGen
