/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: outputs/contracts/openapi.snapshot.json
 * Snapshot SHA256: 25b8a8b16d8d391fa6a7a63add4ea7f68aab4d9b888d3c432ea6cde5f58fdf3c
 * Generated at: 2026-02-10T22:10:47.103Z
 *
 * To regenerate: npm run gen:api
 */

import * as http from '@platform/http'

export const skillosServiceGen: any = {
  /** Disable Extension */
  async disableExtensionApiExtensionsExtensionIdDisablePost(extension_id: any, data?: any): Promise<any> {
    return http.post(`/api/extensions/${extension_id}/disable`, data)
  },

  /** Enable Extension */
  async enableExtensionApiExtensionsExtensionIdEnablePost(extension_id: any, data?: any): Promise<any> {
    return http.post(`/api/extensions/${extension_id}/enable`, data)
  },

  /** Delete Extension */
  async deleteExtensionApiExtensionsExtensionIdDelete(extension_id: any): Promise<any> {
    return http.del(`/api/extensions/${extension_id}`)
  },

  /** List Extensions */
  async listExtensionsApiExtensionsGet(_params?: any): Promise<any> {
    return http.get('/api/extensions', _params ? { params: _params } : undefined)
  },

  /** Get Skill */
  async getSkillApiSkillsSkillIdGet(skill_id: any, _params?: any): Promise<any> {
    return http.get(`/api/skills/${skill_id}`, _params ? { params: _params } : undefined)
  },

  /** Install Skill */
  async installSkillApiSkillsInstallPost(data?: any): Promise<any> {
    return http.post('/api/skills/install', data)
  },

  /** List Skills */
  async listSkillsApiSkillsGet(_params?: any): Promise<any> {
    return http.get('/api/skills', _params ? { params: _params } : undefined)
  }
}

export type skillosServiceGenApi = typeof skillosServiceGen
