/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * Generated by: scripts/gen-api.ts
 * Source: outputs/contracts/openapi.snapshot.json
 * Snapshot SHA256: 25b8a8b16d8d391fa6a7a63add4ea7f68aab4d9b888d3c432ea6cde5f58fdf3c
 * Generated at: 2026-02-10T22:10:47.105Z
 *
 * To regenerate: npm run gen:api
 */

import * as http from '@platform/http'

export const systemServiceGen: any = {
  /** Validate Token */
  async validateTokenApiAdminTokenValidateGet(_params?: any): Promise<any> {
    return http.get('/api/admin/token/validate', _params ? { params: _params } : undefined)
  },

  /** List Agents */
  async listAgentsApiAgentsGet(_params?: any): Promise<any> {
    return http.get('/api/agents', _params ? { params: _params } : undefined)
  },

  /** Get Answer Pack */
  async getAnswerPackApiAnswersPacksPackIdGet(pack_id: any, _params?: any): Promise<any> {
    return http.get(`/api/answers/packs/${pack_id}`, _params ? { params: _params } : undefined)
  },

  /** List Answer Packs */
  async listAnswerPacksApiAnswersPacksGet(_params?: any): Promise<any> {
    return http.get('/api/answers/packs', _params ? { params: _params } : undefined)
  },

  /** Create Answer Pack */
  async createAnswerPackApiAnswersPacksPost(data?: any): Promise<any> {
    return http.post('/api/answers/packs', data)
  },

  /** Validate Auth Profile */
  async validateAuthProfileApiAuthProfilesProfileIdValidatePost(profile_id: any, data?: any): Promise<any> {
    return http.post(`/api/auth/profiles/${profile_id}/validate`, data)
  },

  /** List Auth Profiles */
  async listAuthProfilesApiAuthProfilesGet(_params?: any): Promise<any> {
    return http.get('/api/auth/profiles', _params ? { params: _params } : undefined)
  },

  /** Brain Blind Spots */
  async brainBlindSpotsApiBrainBlindSpotsGet(_params?: any): Promise<any> {
    return http.get('/api/brain/blind-spots', _params ? { params: _params } : undefined)
  },

  /** Brain Build */
  async brainBuildApiBrainBuildPost(data?: any): Promise<any> {
    return http.post('/api/brain/build', data)
  },

  /** Brain Coverage */
  async brainCoverageApiBrainCoverageGet(_params?: any): Promise<any> {
    return http.get('/api/brain/coverage', _params ? { params: _params } : undefined)
  },

  /** Brain Dashboard */
  async brainDashboardApiBrainDashboardGet(_params?: any): Promise<any> {
    return http.get('/api/brain/dashboard', _params ? { params: _params } : undefined)
  },

  /** Replay Brain Governance Decision */
  async replayBrainGovernanceDecisionApiBrainGovernanceDecisionsDecisionIdReplayGet(decision_id: any, _params?: any): Promise<any> {
    return http.get(`/api/brain/governance/decisions/${decision_id}/replay`, _params ? { params: _params } : undefined)
  },

  /** Signoff Brain Governance Decision */
  async signoffBrainGovernanceDecisionApiBrainGovernanceDecisionsDecisionIdSignoffPost(decision_id: any, data?: any): Promise<any> {
    return http.post(`/api/brain/governance/decisions/${decision_id}/signoff`, data)
  },

  /** Get Brain Governance Decision */
  async getBrainGovernanceDecisionApiBrainGovernanceDecisionsDecisionIdGet(decision_id: any, _params?: any): Promise<any> {
    return http.get(`/api/brain/governance/decisions/${decision_id}`, _params ? { params: _params } : undefined)
  },

  /** List Brain Governance Decisions */
  async listBrainGovernanceDecisionsApiBrainGovernanceDecisionsGet(_params?: any): Promise<any> {
    return http.get('/api/brain/governance/decisions', _params ? { params: _params } : undefined)
  },

  /** Brain Knowledge Health */
  async brainKnowledgeHealthApiBrainKnowledgeHealthGet(_params?: any): Promise<any> {
    return http.get('/api/brain/knowledge-health', _params ? { params: _params } : undefined)
  },

  /** Brain Stats */
  async brainStatsApiBrainStatsGet(_params?: any): Promise<any> {
    return http.get('/api/brain/stats', _params ? { params: _params } : undefined)
  },

  /** Brain Subgraph */
  async brainSubgraphApiBrainSubgraphGet(_params?: any): Promise<any> {
    return http.get('/api/brain/subgraph', _params ? { params: _params } : undefined)
  },

  /** Get Budget Global */
  async getBudgetGlobalApiBudgetGlobalGet(_params?: any): Promise<any> {
    return http.get('/api/budget/global', _params ? { params: _params } : undefined)
  },

  /** Put Budget Global */
  async putBudgetGlobalApiBudgetGlobalPut(data?: any): Promise<any> {
    return http.put('/api/budget/global', data)
  },

  /** Transfer Sip Call */
  async transferSipCallApiCallsSessionsCallSessionIdChannelsSipTransferPost(call_session_id: any, data?: any): Promise<any> {
    return http.post(`/api/calls/sessions/${call_session_id}/channels/sip/transfer`, data)
  },

  /** Start Twilio Channel */
  async startTwilioChannelApiCallsSessionsCallSessionIdChannelsTwilioStartPost(call_session_id: any, data?: any): Promise<any> {
    return http.post(`/api/calls/sessions/${call_session_id}/channels/twilio/start`, data)
  },

  /** Create Webrtc Answer */
  async createWebrtcAnswerApiCallsSessionsCallSessionIdChannelsWebrtcOfferPost(call_session_id: any, data?: any): Promise<any> {
    return http.post(`/api/calls/sessions/${call_session_id}/channels/webrtc/offer`, data)
  },

  /** List Call Events */
  async listCallEventsApiCallsSessionsCallSessionIdEventsGet(call_session_id: any, _params?: any): Promise<any> {
    return http.get(`/api/calls/sessions/${call_session_id}/events`, _params ? { params: _params } : undefined)
  },

  /** Start Call Recording */
  async startCallRecordingApiCallsSessionsCallSessionIdRecordingStartPost(call_session_id: any, data?: any): Promise<any> {
    return http.post(`/api/calls/sessions/${call_session_id}/recording/start`, data)
  },

  /** Stop Call Recording */
  async stopCallRecordingApiCallsSessionsCallSessionIdRecordingStopPost(call_session_id: any, data?: any): Promise<any> {
    return http.post(`/api/calls/sessions/${call_session_id}/recording/stop`, data)
  },

  /** Get Call Task */
  async getCallTaskApiCallsSessionsCallSessionIdTaskGet(call_session_id: any, _params?: any): Promise<any> {
    return http.get(`/api/calls/sessions/${call_session_id}/task`, _params ? { params: _params } : undefined)
  },

  /** List Call Transcripts */
  async listCallTranscriptsApiCallsSessionsCallSessionIdTranscriptsGet(call_session_id: any, _params?: any): Promise<any> {
    return http.get(`/api/calls/sessions/${call_session_id}/transcripts`, _params ? { params: _params } : undefined)
  },

  /** Get Call Session */
  async getCallSessionApiCallsSessionsCallSessionIdGet(call_session_id: any, _params?: any): Promise<any> {
    return http.get(`/api/calls/sessions/${call_session_id}`, _params ? { params: _params } : undefined)
  },

  /** Create Call Session */
  async createCallSessionApiCallsSessionsPost(data?: any): Promise<any> {
    return http.post('/api/calls/sessions', data)
  },

  /** Capability Dashboard Stats */
  async capabilityDashboardStatsApiCapabilityDashboardStatsGet(_params?: any): Promise<any> {
    return http.get('/api/capability/dashboard/stats', _params ? { params: _params } : undefined)
  },

  /** Capability Governance Audit */
  async capabilityGovernanceAuditApiCapabilityGovernanceAuditGet(_params?: any): Promise<any> {
    return http.get('/api/capability/governance/audit', _params ? { params: _params } : undefined)
  },

  /** Changelog Entry */
  async changelogEntryApiChangelogEntryGet(_params?: any): Promise<any> {
    return http.get('/api/changelog/entry', _params ? { params: _params } : undefined)
  },

  /** Changelog Index */
  async changelogIndexApiChangelogIndexGet(_params?: any): Promise<any> {
    return http.get('/api/changelog/index', _params ? { params: _params } : undefined)
  },

  /** List Channels Marketplace */
  async listChannelsMarketplaceApiChannelsMarketplaceGet(_params?: any): Promise<any> {
    return http.get('/api/channels-marketplace', _params ? { params: _params } : undefined)
  },

  /** Switch Binding */
  async switchBindingApiChannelsChannelIdBindingsBindingIdSwitchPost(channel_id: any, binding_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/bindings/${binding_id}/switch`, data)
  },

  /** List Bindings */
  async listBindingsApiChannelsChannelIdBindingsGet(channel_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/${channel_id}/bindings`, _params ? { params: _params } : undefined)
  },

  /** Get Channel Config */
  async getChannelConfigApiChannelsChannelIdConfigGet(channel_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/${channel_id}/config`, _params ? { params: _params } : undefined)
  },

  /** Configure Channel */
  async configureChannelApiChannelsChannelIdConfigurePost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/configure`, data)
  },

  /** Connect Channel */
  async connectChannelApiChannelsChannelIdConnectPost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/connect`, data)
  },

  /** Disable Channel */
  async disableChannelApiChannelsChannelIdDisablePost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/disable`, data)
  },

  /** Enable Channel */
  async enableChannelApiChannelsChannelIdEnablePost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/enable`, data)
  },

  /** Channel Qr */
  async channelQrApiChannelsChannelIdQrGet(channel_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/${channel_id}/qr`, _params ? { params: _params } : undefined)
  },

  /** Send Message Tool */
  async sendMessageToolApiChannelsChannelIdSendPost(channel_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/${channel_id}/send`, data)
  },

  /** Channel Status */
  async channelStatusApiChannelsChannelIdStatusGet(channel_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/${channel_id}/status`, _params ? { params: _params } : undefined)
  },

  /** Draft Reply */
  async draftReplyApiChannelsEmailInstanceIdDraftReplyPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/draft-reply`, data)
  },

  /** Mark Read */
  async markReadApiChannelsEmailInstanceIdMarkReadPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/mark-read`, data)
  },

  /** Get Message */
  async getMessageApiChannelsEmailInstanceIdMessageMessageIdGet(instance_id: any, message_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/email/${instance_id}/message/${message_id}`, _params ? { params: _params } : undefined)
  },

  /** Oauth Disconnect */
  async oauthDisconnectApiChannelsEmailInstanceIdOauthDisconnectPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/oauth/disconnect`, data)
  },

  /** Oauth Start */
  async oauthStartApiChannelsEmailInstanceIdOauthStartGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/email/${instance_id}/oauth/start`, _params ? { params: _params } : undefined)
  },

  /** Oauth Status */
  async oauthStatusApiChannelsEmailInstanceIdOauthStatusGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/email/${instance_id}/oauth/status`, _params ? { params: _params } : undefined)
  },

  /** Send Draft */
  async sendDraftApiChannelsEmailInstanceIdSendPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/send`, data)
  },

  /** Snooze Message */
  async snoozeMessageApiChannelsEmailInstanceIdSnoozePost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/${instance_id}/snooze`, data)
  },

  /** List Unread */
  async listUnreadApiChannelsEmailInstanceIdUnreadGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/channels/email/${instance_id}/unread`, _params ? { params: _params } : undefined)
  },

  /** Allow Sender */
  async allowSenderApiChannelsEmailInstancesInstanceIdRulesAllowSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/allow_sender`, data)
  },

  /** Block Domain */
  async blockDomainApiChannelsEmailInstancesInstanceIdRulesBlockDomainPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/block_domain`, data)
  },

  /** Block Sender */
  async blockSenderApiChannelsEmailInstancesInstanceIdRulesBlockSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/block_sender`, data)
  },

  /** Unblock Domain */
  async unblockDomainApiChannelsEmailInstancesInstanceIdRulesUnblockDomainPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/unblock_domain`, data)
  },

  /** Unblock Sender */
  async unblockSenderApiChannelsEmailInstancesInstanceIdRulesUnblockSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/rules/unblock_sender`, data)
  },

  /** Test Instance */
  async testInstanceApiChannelsEmailInstancesInstanceIdTestPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/channels/email/instances/${instance_id}/test`, data)
  },

  /** List Instances */
  async listInstancesApiChannelsEmailInstancesGet(_params?: any): Promise<any> {
    return http.get('/api/channels/email/instances', _params ? { params: _params } : undefined)
  },

  /** Create Instance */
  async createInstanceApiChannelsEmailInstancesPost(data?: any): Promise<any> {
    return http.post('/api/channels/email/instances', data)
  },

  /** Oauth Callback */
  async oauthCallbackApiChannelsEmailOauthCallbackGet(_params?: any): Promise<any> {
    return http.get('/api/channels/email/oauth/callback', _params ? { params: _params } : undefined)
  },

  /** List Configured Channels */
  async listConfiguredChannelsApiChannelsGet(_params?: any): Promise<any> {
    return http.get('/api/channels', _params ? { params: _params } : undefined)
  },

  /** List Comm Audits */
  async listCommAuditsApiCommunicationAuditsGet(_params?: any): Promise<any> {
    return http.get('/api/communication/audits', _params ? { params: _params } : undefined)
  },

  /** Get Comm Mode */
  async getCommModeApiCommunicationModeGet(_params?: any): Promise<any> {
    return http.get('/api/communication/mode', _params ? { params: _params } : undefined)
  },

  /** Set Comm Mode */
  async setCommModeApiCommunicationModePut(data?: any): Promise<any> {
    return http.put('/api/communication/mode', data)
  },

  /** Get Comm Policy */
  async getCommPolicyApiCommunicationPolicyGet(_params?: any): Promise<any> {
    return http.get('/api/communication/policy', _params ? { params: _params } : undefined)
  },

  /** Get Comm Status */
  async getCommStatusApiCommunicationStatusGet(_params?: any): Promise<any> {
    return http.get('/api/communication/status', _params ? { params: _params } : undefined)
  },

  /** Uninstall MCP package (Deprecated Alias) */
  async uninstallMcpPackageAliasApiCommunicationosMcpPackagesPackageIdUninstallDelete(package_id: any): Promise<any> {
    return http.del(`/api/communicationos/mcp/packages/${package_id}/uninstall`)
  },

  /** Apply Profile */
  async applyProfileApiCompatConnectorsConnectorIdEndpointsEndpointIdApplyProfilePost(connector_id: any, endpoint_id: any, data?: any): Promise<any> {
    return http.post(`/api/compat/connectors/${connector_id}/endpoints/${endpoint_id}/apply-profile`, data)
  },

  /** Infer Profile */
  async inferProfileApiCompatConnectorsConnectorIdEndpointsEndpointIdInferProfilePost(connector_id: any, endpoint_id: any, data?: any): Promise<any> {
    return http.post(`/api/compat/connectors/${connector_id}/endpoints/${endpoint_id}/infer-profile`, data)
  },

  /** List Profiles */
  async listProfilesApiCompatConnectorsConnectorIdEndpointsEndpointIdProfilesGet(connector_id: any, endpoint_id: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/connectors/${connector_id}/endpoints/${endpoint_id}/profiles`, _params ? { params: _params } : undefined)
  },

  /** Test Endpoint */
  async testEndpointApiCompatConnectorsConnectorIdEndpointsEndpointIdTestPost(connector_id: any, endpoint_id: any, data?: any): Promise<any> {
    return http.post(`/api/compat/connectors/${connector_id}/endpoints/${endpoint_id}/test`, data)
  },

  /** Get Usage Card */
  async getUsageCardApiCompatConnectorsConnectorIdEndpointsEndpointIdUsageCardGet(connector_id: any, endpoint_id: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/connectors/${connector_id}/endpoints/${endpoint_id}/usage-card`, _params ? { params: _params } : undefined)
  },

  /** Delete Endpoint */
  async deleteEndpointApiCompatConnectorsConnectorIdEndpointsEndpointIdDelete(connector_id: any, endpoint_id: any): Promise<any> {
    return http.del(`/api/compat/connectors/${connector_id}/endpoints/${endpoint_id}`)
  },

  /** List Endpoints */
  async listEndpointsApiCompatConnectorsConnectorIdEndpointsGet(connector_id: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/connectors/${connector_id}/endpoints`, _params ? { params: _params } : undefined)
  },

  /** Upsert Endpoint */
  async upsertEndpointApiCompatConnectorsConnectorIdEndpointsPost(connector_id: any, data?: any): Promise<any> {
    return http.post(`/api/compat/connectors/${connector_id}/endpoints`, data)
  },

  /** List Import Versions */
  async listImportVersionsApiCompatConnectorsConnectorIdImportVersionsGet(connector_id: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/connectors/${connector_id}/import-versions`, _params ? { params: _params } : undefined)
  },

  /** Import Openapi Url */
  async importOpenapiUrlApiCompatConnectorsConnectorIdImportOpenapiUrlPost(connector_id: any, data?: any): Promise<any> {
    return http.post(`/api/compat/connectors/${connector_id}/import/openapi-url`, data)
  },

  /** Import Openapi */
  async importOpenapiApiCompatConnectorsConnectorIdImportOpenapiPost(connector_id: any, data?: any): Promise<any> {
    return http.post(`/api/compat/connectors/${connector_id}/import/openapi`, data)
  },

  /** Delete Connector */
  async deleteConnectorApiCompatConnectorsConnectorIdDelete(connector_id: any): Promise<any> {
    return http.del(`/api/compat/connectors/${connector_id}`)
  },

  /** Get Connector */
  async getConnectorApiCompatConnectorsConnectorIdGet(connector_id: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/connectors/${connector_id}`, _params ? { params: _params } : undefined)
  },

  /** Import Openapi Url Deprecated */
  async importOpenapiUrlDeprecatedApiCompatConnectorsImportOpenapiUrlPost(data?: any): Promise<any> {
    return http.post('/api/compat/connectors/import/openapi-url', data)
  },

  /** Import Openapi Deprecated */
  async importOpenapiDeprecatedApiCompatConnectorsImportOpenapiPost(data?: any): Promise<any> {
    return http.post('/api/compat/connectors/import/openapi', data)
  },

  /** Search Endpoints */
  async searchEndpointsApiCompatConnectorsSearchEndpointsAllGet(_params?: any): Promise<any> {
    return http.get('/api/compat/connectors/search/endpoints/all', _params ? { params: _params } : undefined)
  },

  /** List Connectors */
  async listConnectorsApiCompatConnectorsGet(_params?: any): Promise<any> {
    return http.get('/api/compat/connectors', _params ? { params: _params } : undefined)
  },

  /** Upsert Connector */
  async upsertConnectorApiCompatConnectorsPost(data?: any): Promise<any> {
    return http.post('/api/compat/connectors', data)
  },

  /** Delete Binding */
  async deleteBindingApiCompatExternalFactsBindingsCapabilityIdItemIdDelete(capability_id: any, item_id: any): Promise<any> {
    return http.del(`/api/compat/external-facts/bindings/${capability_id}/${item_id}`)
  },

  /** List Bindings */
  async listBindingsApiCompatExternalFactsBindingsGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/bindings', _params ? { params: _params } : undefined)
  },

  /** Upsert Binding */
  async upsertBindingApiCompatExternalFactsBindingsPost(data?: any): Promise<any> {
    return http.post('/api/compat/external-facts/bindings', data)
  },

  /** List Extractions */
  async listExtractionsApiCompatExternalFactsEvidenceEvidenceIdExtractionsGet(evidence_id: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/external-facts/evidence/${evidence_id}/extractions`, _params ? { params: _params } : undefined)
  },

  /** List Verifications */
  async listVerificationsApiCompatExternalFactsEvidenceEvidenceIdVerificationsGet(evidence_id: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/external-facts/evidence/${evidence_id}/verifications`, _params ? { params: _params } : undefined)
  },

  /** Get Evidence */
  async getEvidenceApiCompatExternalFactsEvidenceEvidenceIdGet(evidence_id: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/external-facts/evidence/${evidence_id}`, _params ? { params: _params } : undefined)
  },

  /** List Policies */
  async listPoliciesApiCompatExternalFactsPolicyListGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/policy/list', _params ? { params: _params } : undefined)
  },

  /** Get Policy */
  async getPolicyApiCompatExternalFactsPolicyGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/policy', _params ? { params: _params } : undefined)
  },

  /** Put Policy */
  async putPolicyApiCompatExternalFactsPolicyPut(data?: any): Promise<any> {
    return http.put('/api/compat/external-facts/policy', data)
  },

  /** Apply Mapping */
  async applyMappingApiCompatExternalFactsProvidersProviderIdEndpointEndpointKeyApplyMappingPost(provider_id: any, endpoint_key: any, data?: any): Promise<any> {
    return http.post(`/api/compat/external-facts/providers/${provider_id}/endpoint/${endpoint_key}/apply-mapping`, data)
  },

  /** Infer Mapping */
  async inferMappingApiCompatExternalFactsProvidersProviderIdEndpointEndpointKeyInferMappingPost(provider_id: any, endpoint_key: any, data?: any): Promise<any> {
    return http.post(`/api/compat/external-facts/providers/${provider_id}/endpoint/${endpoint_key}/infer-mapping`, data)
  },

  /** List Mappings */
  async listMappingsApiCompatExternalFactsProvidersProviderIdEndpointEndpointKeyMappingsGet(provider_id: any, endpoint_key: any, _params?: any): Promise<any> {
    return http.get(`/api/compat/external-facts/providers/${provider_id}/endpoint/${endpoint_key}/mappings`, _params ? { params: _params } : undefined)
  },

  /** Test Provider */
  async testProviderApiCompatExternalFactsProvidersProviderIdTestPost(provider_id: any, data?: any): Promise<any> {
    return http.post(`/api/compat/external-facts/providers/${provider_id}/test`, data)
  },

  /** Delete Provider */
  async deleteProviderApiCompatExternalFactsProvidersProviderIdDelete(provider_id: any): Promise<any> {
    return http.del(`/api/compat/external-facts/providers/${provider_id}`)
  },

  /** List Providers */
  async listProvidersApiCompatExternalFactsProvidersGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/providers', _params ? { params: _params } : undefined)
  },

  /** Upsert Provider */
  async upsertProviderApiCompatExternalFactsProvidersPost(data?: any): Promise<any> {
    return http.post('/api/compat/external-facts/providers', data)
  },

  /** List Recent Evidence */
  async listRecentEvidenceApiCompatExternalFactsRecentGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/recent', _params ? { params: _params } : undefined)
  },

  /** Get External Facts Registry */
  async getExternalFactsRegistryApiCompatExternalFactsRegistryGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/registry', _params ? { params: _params } : undefined)
  },

  /** Apply Schemas */
  async applySchemasApiCompatExternalFactsSchemaApplyPut(data?: any): Promise<any> {
    return http.put('/api/compat/external-facts/schema/apply', data)
  },

  /** Export Schemas */
  async exportSchemasApiCompatExternalFactsSchemaExportGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/schema/export', _params ? { params: _params } : undefined)
  },

  /** Schema History */
  async schemaHistoryApiCompatExternalFactsSchemaHistoryGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/schema/history', _params ? { params: _params } : undefined)
  },

  /** Rollback Schema */
  async rollbackSchemaApiCompatExternalFactsSchemaRollbackPost(data?: any): Promise<any> {
    return http.post('/api/compat/external-facts/schema/rollback', data)
  },

  /** List Schemas */
  async listSchemasApiCompatExternalFactsSchemaGet(_params?: any): Promise<any> {
    return http.get('/api/compat/external-facts/schema', _params ? { params: _params } : undefined)
  },

  /** Config Allowlist Get */
  async configAllowlistGetApiConfigAllowlistGet(_params?: any): Promise<any> {
    return http.get('/api/config/allowlist', _params ? { params: _params } : undefined)
  },

  /** Config Diff Get */
  async configDiffGetApiConfigDiffGet(_params?: any): Promise<any> {
    return http.get('/api/config/diff', _params ? { params: _params } : undefined)
  },

  /** Config Entry Delete */
  async configEntryDeleteApiConfigEntriesIdDelete(id: any): Promise<any> {
    return http.del(`/api/config/entries/${id}`)
  },

  /** Config Entry Update */
  async configEntryUpdateApiConfigEntriesIdPut(id: any, data?: any): Promise<any> {
    return http.put(`/api/config/entries/${id}`, data)
  },

  /** Config Entry Get */
  async configEntryGetApiConfigEntriesKeyGet(key: any, _params?: any): Promise<any> {
    return http.get(`/api/config/entries/${key}`, _params ? { params: _params } : undefined)
  },

  /** Config Entries Get */
  async configEntriesGetApiConfigEntriesGet(_params?: any): Promise<any> {
    return http.get('/api/config/entries', _params ? { params: _params } : undefined)
  },

  /** Config Entry Create */
  async configEntryCreateApiConfigEntriesPost(data?: any): Promise<any> {
    return http.post('/api/config/entries', data)
  },

  /** Config Modules Get */
  async configModulesGetApiConfigModulesGet(_params?: any): Promise<any> {
    return http.get('/api/config/modules', _params ? { params: _params } : undefined)
  },

  /** Config Resolve Get */
  async configResolveGetApiConfigResolveGet(_params?: any): Promise<any> {
    return http.get('/api/config/resolve', _params ? { params: _params } : undefined)
  },

  /** Config Rollback From Snapshot */
  async configRollbackFromSnapshotApiConfigRollbackFromSnapshotPost(data?: any): Promise<any> {
    return http.post('/api/config/rollback_from_snapshot', data)
  },

  /** Config Rollback */
  async configRollbackApiConfigRollbackPost(data?: any): Promise<any> {
    return http.post('/api/config/rollback', data)
  },

  /** Config Secret Status */
  async configSecretStatusApiConfigSecretStatusGet(_params?: any): Promise<any> {
    return http.get('/api/config/secret-status', _params ? { params: _params } : undefined)
  },

  /** Config Snapshot Get */
  async configSnapshotGetApiConfigSnapshotSnapshotIdGet(snapshot_id: any, _params?: any): Promise<any> {
    return http.get(`/api/config/snapshot/${snapshot_id}`, _params ? { params: _params } : undefined)
  },

  /** Config Snapshot Create */
  async configSnapshotCreateApiConfigSnapshotPost(data?: any): Promise<any> {
    return http.post('/api/config/snapshot', data)
  },

  /** Config Timeline Get */
  async configTimelineGetApiConfigTimelineGet(_params?: any): Promise<any> {
    return http.get('/api/config/timeline', _params ? { params: _params } : undefined)
  },

  /** Config Get */
  async configGetApiConfigGet(_params?: any): Promise<any> {
    return http.get('/api/config', _params ? { params: _params } : undefined)
  },

  /** Activate Content */
  async activateContentApiContentContentIdActivatePost(content_id: any, data?: any): Promise<any> {
    return http.post(`/api/content/${content_id}/activate`, data)
  },

  /** Deprecate Content */
  async deprecateContentApiContentContentIdDeprecatePost(content_id: any, data?: any): Promise<any> {
    return http.post(`/api/content/${content_id}/deprecate`, data)
  },

  /** Freeze Content */
  async freezeContentApiContentContentIdFreezePost(content_id: any, data?: any): Promise<any> {
    return http.post(`/api/content/${content_id}/freeze`, data)
  },

  /** Get Content */
  async getContentApiContentContentIdGet(content_id: any, _params?: any): Promise<any> {
    return http.get(`/api/content/${content_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Content */
  async updateContentApiContentContentIdPut(content_id: any, data?: any): Promise<any> {
    return http.put(`/api/content/${content_id}`, data)
  },

  /** List Content */
  async listContentApiContentGet(_params?: any): Promise<any> {
    return http.get('/api/content', _params ? { params: _params } : undefined)
  },

  /** Create Content */
  async createContentApiContentPost(data?: any): Promise<any> {
    return http.post('/api/content', data)
  },

  /** Context Attach */
  async contextAttachApiContextAttachPost(data?: any): Promise<any> {
    return http.post('/api/context/attach', data)
  },

  /** Context Detach */
  async contextDetachApiContextDetachPost(data?: any): Promise<any> {
    return http.post('/api/context/detach', data)
  },

  /** Context Refresh */
  async contextRefreshApiContextRefreshPost(data?: any): Promise<any> {
    return http.post('/api/context/refresh', data)
  },

  /** Get Context Status */
  async getContextStatusApiContextStatusGet(_params?: any): Promise<any> {
    return http.get('/api/context/status', _params ? { params: _params } : undefined)
  },

  /** Daemon Control Token */
  async daemonControlTokenApiDaemonControlTokenGet(_params?: any): Promise<any> {
    return http.get('/api/daemon/control-token', _params ? { params: _params } : undefined)
  },

  /** Daemon Logs */
  async daemonLogsApiDaemonLogsGet(_params?: any): Promise<any> {
    return http.get('/api/daemon/logs', _params ? { params: _params } : undefined)
  },

  /** Daemon Restart */
  async daemonRestartApiDaemonRestartPost(data?: any): Promise<any> {
    return http.post('/api/daemon/restart', data)
  },

  /** Daemon Start */
  async daemonStartApiDaemonStartPost(data?: any): Promise<any> {
    return http.post('/api/daemon/start', data)
  },

  /** Daemon Status */
  async daemonStatusApiDaemonStatusGet(_params?: any): Promise<any> {
    return http.get('/api/daemon/status', _params ? { params: _params } : undefined)
  },

  /** Daemon Stop */
  async daemonStopApiDaemonStopPost(data?: any): Promise<any> {
    return http.post('/api/daemon/stop', data)
  },

  /** Demo Mode Disable */
  async demoModeDisableApiDemoModeDisablePost(data?: any): Promise<any> {
    return http.post('/api/demo-mode/disable', data)
  },

  /** Demo Mode Enable */
  async demoModeEnableApiDemoModeEnablePost(data?: any): Promise<any> {
    return http.post('/api/demo-mode/enable', data)
  },

  /** Demo Mode Status */
  async demoModeStatusApiDemoModeStatusGet(_params?: any): Promise<any> {
    return http.get('/api/demo-mode/status', _params ? { params: _params } : undefined)
  },

  /** Approve Device */
  async approveDeviceApiDevicesRequestIdApprovePost(request_id: any, data?: any): Promise<any> {
    return http.post(`/api/devices/${request_id}/approve`, data)
  },

  /** Reject Device */
  async rejectDeviceApiDevicesRequestIdRejectPost(request_id: any, data?: any): Promise<any> {
    return http.post(`/api/devices/${request_id}/reject`, data)
  },

  /** Revoke Device */
  async revokeDeviceApiDevicesRequestIdRevokePost(request_id: any, data?: any): Promise<any> {
    return http.post(`/api/devices/${request_id}/revoke`, data)
  },

  /** List Approved */
  async listApprovedApiDevicesApprovedGet(_params?: any): Promise<any> {
    return http.get('/api/devices/approved', _params ? { params: _params } : undefined)
  },

  /** Pair Status */
  async pairStatusApiDevicesPairRequestIdStatusGet(request_id: any, _params?: any): Promise<any> {
    return http.get(`/api/devices/pair/${request_id}/status`, _params ? { params: _params } : undefined)
  },

  /** Create Pairing Code */
  async createPairingCodeApiDevicesPairingCodeCreatePost(data?: any): Promise<any> {
    return http.post('/api/devices/pairing-code/create', data)
  },

  /** Pair Device */
  async pairDeviceApiDevicesPairPost(data?: any): Promise<any> {
    return http.post('/api/devices/pair', data)
  },

  /** List Pending */
  async listPendingApiDevicesPendingGet(_params?: any): Promise<any> {
    return http.get('/api/devices/pending', _params ? { params: _params } : undefined)
  },

  /** Export Diagnostic Bundle */
  async exportDiagnosticBundleApiDiagnosticExportPost(data?: any): Promise<any> {
    return http.post('/api/diagnostic/export', data)
  },

  /** Cancel Job */
  async cancelJobApiDispatchJobsJobIdCancelPost(job_id: any, data?: any): Promise<any> {
    return http.post(`/api/dispatch/jobs/${job_id}/cancel`, data)
  },

  /** Retry Job */
  async retryJobApiDispatchJobsJobIdRetryPost(job_id: any, data?: any): Promise<any> {
    return http.post(`/api/dispatch/jobs/${job_id}/retry`, data)
  },

  /** Rollback Job */
  async rollbackJobApiDispatchJobsJobIdRollbackPost(job_id: any, data?: any): Promise<any> {
    return http.post(`/api/dispatch/jobs/${job_id}/rollback`, data)
  },

  /** Get Job */
  async getJobApiDispatchJobsJobIdGet(job_id: any, _params?: any): Promise<any> {
    return http.get(`/api/dispatch/jobs/${job_id}`, _params ? { params: _params } : undefined)
  },

  /** List Jobs */
  async listJobsApiDispatchJobsGet(_params?: any): Promise<any> {
    return http.get('/api/dispatch/jobs', _params ? { params: _params } : undefined)
  },

  /** Approve Proposal */
  async approveProposalApiDispatchProposalsProposalIdApprovePost(proposal_id: any, data?: any): Promise<any> {
    return http.post(`/api/dispatch/proposals/${proposal_id}/approve`, data)
  },

  /** Execute Proposal */
  async executeProposalApiDispatchProposalsProposalIdExecutePost(proposal_id: any, data?: any): Promise<any> {
    return http.post(`/api/dispatch/proposals/${proposal_id}/execute`, data)
  },

  /** Reject Proposal */
  async rejectProposalApiDispatchProposalsProposalIdRejectPost(proposal_id: any, data?: any): Promise<any> {
    return http.post(`/api/dispatch/proposals/${proposal_id}/reject`, data)
  },

  /** Get Proposal */
  async getProposalApiDispatchProposalsProposalIdGet(proposal_id: any, _params?: any): Promise<any> {
    return http.get(`/api/dispatch/proposals/${proposal_id}`, _params ? { params: _params } : undefined)
  },

  /** List Proposals */
  async listProposalsApiDispatchProposalsGet(_params?: any): Promise<any> {
    return http.get('/api/dispatch/proposals', _params ? { params: _params } : undefined)
  },

  /** Create Proposal */
  async createProposalApiDispatchProposalsPost(data?: any): Promise<any> {
    return http.post('/api/dispatch/proposals', data)
  },

  /** Connect Platform */
  async connectPlatformApiEnterpriseImPlatformConnectPost(platform: any, data?: any): Promise<any> {
    return http.post(`/api/enterprise-im/${platform}/connect`, data)
  },

  /** Disconnect Platform */
  async disconnectPlatformApiEnterpriseImPlatformDisconnectPost(platform: any, data?: any): Promise<any> {
    return http.post(`/api/enterprise-im/${platform}/disconnect`, data)
  },

  /** Platform Status */
  async platformStatusApiEnterpriseImPlatformStatusGet(platform: any, _params?: any): Promise<any> {
    return http.get(`/api/enterprise-im/${platform}/status`, _params ? { params: _params } : undefined)
  },

  /** Platform Webhook */
  async platformWebhookApiEnterpriseImPlatformWebhookPost(platform: any, data?: any): Promise<any> {
    return http.post(`/api/enterprise-im/${platform}/webhook`, data)
  },

  /** List Enterprise Events */
  async listEnterpriseEventsApiEnterpriseImEventsGet(_params?: any): Promise<any> {
    return http.get('/api/enterprise-im/events', _params ? { params: _params } : undefined)
  },

  /** List Events */
  async listEventsApiEventsGet(_params?: any): Promise<any> {
    return http.get('/api/events', _params ? { params: _params } : undefined)
  },

  /** Delete Execution Policy */
  async deleteExecutionPolicyApiExecutionPoliciesPolicyIdDelete(policy_id: any): Promise<any> {
    return http.del(`/api/execution/policies/${policy_id}`)
  },

  /** Update Execution Policy */
  async updateExecutionPolicyApiExecutionPoliciesPolicyIdPut(policy_id: any, data?: any): Promise<any> {
    return http.put(`/api/execution/policies/${policy_id}`, data)
  },

  /** List Execution Policies */
  async listExecutionPoliciesApiExecutionPoliciesGet(_params?: any): Promise<any> {
    return http.get('/api/execution/policies', _params ? { params: _params } : undefined)
  },

  /** Create Execution Policy */
  async createExecutionPolicyApiExecutionPoliciesPost(data?: any): Promise<any> {
    return http.post('/api/execution/policies', data)
  },

  /** Disable Extension */
  async disableExtensionApiExtensionsExtensionIdDisablePost(extension_id: any, data?: any): Promise<any> {
    return http.post(`/api/extensions/${extension_id}/disable`, data)
  },

  /** Enable Extension */
  async enableExtensionApiExtensionsExtensionIdEnablePost(extension_id: any, data?: any): Promise<any> {
    return http.post(`/api/extensions/${extension_id}/enable`, data)
  },

  /** Delete Extension */
  async deleteExtensionApiExtensionsExtensionIdDelete(extension_id: any): Promise<any> {
    return http.del(`/api/extensions/${extension_id}`)
  },

  /** List Extensions */
  async listExtensionsApiExtensionsGet(_params?: any): Promise<any> {
    return http.get('/api/extensions', _params ? { params: _params } : undefined)
  },

  /** Connect Federation Node */
  async connectFederationNodeApiFederationNodesNodeIdConnectPost(node_id: any, data?: any): Promise<any> {
    return http.post(`/api/federation/nodes/${node_id}/connect`, data)
  },

  /** Disconnect Federation Node */
  async disconnectFederationNodeApiFederationNodesNodeIdDisconnectPost(node_id: any, data?: any): Promise<any> {
    return http.post(`/api/federation/nodes/${node_id}/disconnect`, data)
  },

  /** List Federation Nodes */
  async listFederationNodesApiFederationNodesGet(_params?: any): Promise<any> {
    return http.get('/api/federation/nodes', _params ? { params: _params } : undefined)
  },

  /** Frontdesk Chat */
  async frontdeskChatApiFrontdeskChatPost(data?: any): Promise<any> {
    return http.post('/api/frontdesk/chat', data)
  },

  /** Frontdesk History */
  async frontdeskHistoryApiFrontdeskHistoryGet(_params?: any): Promise<any> {
    return http.get('/api/frontdesk/history', _params ? { params: _params } : undefined)
  },

  /** Frontdesk Overview */
  async frontdeskOverviewApiFrontdeskOverviewGet(_params?: any): Promise<any> {
    return http.get('/api/frontdesk/overview', _params ? { params: _params } : undefined)
  },

  /** Get Evolution Decision */
  async getEvolutionDecisionApiGovernanceEvolutionDecisionsDecisionIdGet(decision_id: any, _params?: any): Promise<any> {
    return http.get(`/api/governance/evolution-decisions/${decision_id}`, _params ? { params: _params } : undefined)
  },

  /** List Evolution Decisions */
  async listEvolutionDecisionsApiGovernanceEvolutionDecisionsGet(_params?: any): Promise<any> {
    return http.get('/api/governance/evolution-decisions', _params ? { params: _params } : undefined)
  },

  /** Delete Governance Finding */
  async deleteGovernanceFindingApiGovernanceFindingsFindingIdDelete(finding_id: any): Promise<any> {
    return http.del(`/api/governance/findings/${finding_id}`)
  },

  /** Get Governance Finding */
  async getGovernanceFindingApiGovernanceFindingsFindingIdGet(finding_id: any, _params?: any): Promise<any> {
    return http.get(`/api/governance/findings/${finding_id}`, _params ? { params: _params } : undefined)
  },

  /** List Governance Findings */
  async listGovernanceFindingsApiGovernanceFindingsGet(_params?: any): Promise<any> {
    return http.get('/api/governance/findings', _params ? { params: _params } : undefined)
  },

  /** List Trust Tiers */
  async listTrustTiersApiGovernanceTrustTiersGet(_params?: any): Promise<any> {
    return http.get('/api/governance/trust-tiers', _params ? { params: _params } : undefined)
  },

  /** Upsert Action Kb Entry */
  async upsertActionKbEntryApiGrowthActionKbEntriesPost(data?: any): Promise<any> {
    return http.post('/api/growth/action-kb/entries', data)
  },

  /** Seed Action Kb */
  async seedActionKbApiGrowthActionKbSeedPost(data?: any): Promise<any> {
    return http.post('/api/growth/action-kb/seed', data)
  },

  /** Failure Decisions */
  async failureDecisionsApiGrowthBrainFailureDecisionsGet(_params?: any): Promise<any> {
    return http.get('/api/growth/brain/failure-decisions', _params ? { params: _params } : undefined)
  },

  /** Growth Metrics */
  async growthMetricsApiGrowthMetricsGet(_params?: any): Promise<any> {
    return http.get('/api/growth/metrics', _params ? { params: _params } : undefined)
  },

  /** Growth Replay Verify */
  async growthReplayVerifyApiGrowthReplayVerifyTaskIdGet(task_id: any, _params?: any): Promise<any> {
    return http.get(`/api/growth/replay-verify/${task_id}`, _params ? { params: _params } : undefined)
  },

  /** Record Kb Execution */
  async recordKbExecutionApiGrowthTasksTaskIdKbExecutionKbIdPost(task_id: any, kb_id: any, data?: any): Promise<any> {
    return http.post(`/api/growth/tasks/${task_id}/kb-execution/${kb_id}`, data)
  },

  /** Require Kb */
  async requireKbApiGrowthTasksTaskIdRequireKbKbIdPost(task_id: any, kb_id: any, data?: any): Promise<any> {
    return http.post(`/api/growth/tasks/${task_id}/require-kb/${kb_id}`, data)
  },

  /** Inbox Badge */
  async inboxBadgeApiInboxBadgeGet(_params?: any): Promise<any> {
    return http.get('/api/inbox/badge', _params ? { params: _params } : undefined)
  },

  /** Ack Card */
  async ackCardApiInboxCardsCardIdAckPost(card_id: any, data?: any): Promise<any> {
    return http.post(`/api/inbox/cards/${card_id}/ack`, data)
  },

  /** Close Card */
  async closeCardApiInboxCardsCardIdClosePost(card_id: any, data?: any): Promise<any> {
    return http.post(`/api/inbox/cards/${card_id}/close`, data)
  },

  /** Defer Card */
  async deferCardApiInboxCardsCardIdDeferPost(card_id: any, data?: any): Promise<any> {
    return http.post(`/api/inbox/cards/${card_id}/defer`, data)
  },

  /** Dismiss Card */
  async dismissCardApiInboxCardsCardIdDismissPost(card_id: any, data?: any): Promise<any> {
    return http.post(`/api/inbox/cards/${card_id}/dismiss`, data)
  },

  /** Resolve Card */
  async resolveCardApiInboxCardsCardIdResolvePost(card_id: any, data?: any): Promise<any> {
    return http.post(`/api/inbox/cards/${card_id}/resolve`, data)
  },

  /** Get Card Detail */
  async getCardDetailApiInboxCardsCardIdGet(card_id: any, _params?: any): Promise<any> {
    return http.get(`/api/inbox/cards/${card_id}`, _params ? { params: _params } : undefined)
  },

  /** Mark Read */
  async markReadApiInboxItemsInboxItemIdMarkReadPost(inbox_item_id: any, data?: any): Promise<any> {
    return http.post(`/api/inbox/items/${inbox_item_id}/mark_read`, data)
  },

  /** List Inbox Items */
  async listInboxItemsApiInboxItemsGet(_params?: any): Promise<any> {
    return http.get('/api/inbox/items', _params ? { params: _params } : undefined)
  },

  /** Info Need Metrics Summary */
  async infoNeedMetricsSummaryApiInfoNeedMetricsSummaryGet(_params?: any): Promise<any> {
    return http.get('/api/info-need-metrics/summary', _params ? { params: _params } : undefined)
  },

  /** List Knowledge Jobs */
  async listKnowledgeJobsApiKnowledgeJobsGet(_params?: any): Promise<any> {
    return http.get('/api/knowledge/jobs', _params ? { params: _params } : undefined)
  },

  /** Create Job */
  async createJobApiKnowledgeJobsPost(data?: any): Promise<any> {
    return http.post('/api/knowledge/jobs', data)
  },

  /** Sync Source */
  async syncSourceApiKnowledgeSourcesSourceIdSyncPost(source_id: any, data?: any): Promise<any> {
    return http.post(`/api/knowledge/sources/${source_id}/sync`, data)
  },

  /** Sync All Sources */
  async syncAllSourcesApiKnowledgeSourcesSyncAllPost(data?: any): Promise<any> {
    return http.post('/api/knowledge/sources/sync-all', data)
  },

  /** List Knowledge Sources */
  async listKnowledgeSourcesApiKnowledgeSourcesGet(_params?: any): Promise<any> {
    return http.get('/api/knowledge/sources', _params ? { params: _params } : undefined)
  },

  /** Create Knowledge Source */
  async createKnowledgeSourceApiKnowledgeSourcesPost(data?: any): Promise<any> {
    return http.post('/api/knowledge/sources', data)
  },

  /** Patch Lead Finding Status */
  async patchLeadFindingStatusApiLeadFindingsFindingIdStatusPatch(finding_id: any, data?: any): Promise<any> {
    return http.patch(`/api/lead/findings/${finding_id}/status`, data)
  },

  /** List Lead Findings */
  async listLeadFindingsApiLeadFindingsGet(_params?: any): Promise<any> {
    return http.get('/api/lead/findings', _params ? { params: _params } : undefined)
  },

  /** List Lead Scans */
  async listLeadScansApiLeadScansGet(_params?: any): Promise<any> {
    return http.get('/api/lead/scans', _params ? { params: _params } : undefined)
  },

  /** Approve Marketplace Capability */
  async approveMarketplaceCapabilityApiMarketplaceCapabilitiesCapabilityIdApprovePost(capability_id: any, data?: any): Promise<any> {
    return http.post(`/api/marketplace/capabilities/${capability_id}/approve`, data)
  },

  /** Reject Marketplace Capability */
  async rejectMarketplaceCapabilityApiMarketplaceCapabilitiesCapabilityIdRejectPost(capability_id: any, data?: any): Promise<any> {
    return http.post(`/api/marketplace/capabilities/${capability_id}/reject`, data)
  },

  /** Get Marketplace Capability */
  async getMarketplaceCapabilityApiMarketplaceCapabilitiesCapabilityIdGet(capability_id: any, _params?: any): Promise<any> {
    return http.get(`/api/marketplace/capabilities/${capability_id}`, _params ? { params: _params } : undefined)
  },

  /** List Marketplace Capabilities */
  async listMarketplaceCapabilitiesApiMarketplaceCapabilitiesGet(_params?: any): Promise<any> {
    return http.get('/api/marketplace/capabilities', _params ? { params: _params } : undefined)
  },

  /** Patch Publisher Trust */
  async patchPublisherTrustApiMarketplacePublishersPublisherIdTrustPatch(publisher_id: any, data?: any): Promise<any> {
    return http.patch(`/api/marketplace/publishers/${publisher_id}/trust`, data)
  },

  /** Get Publisher */
  async getPublisherApiMarketplacePublishersPublisherIdGet(publisher_id: any, _params?: any): Promise<any> {
    return http.get(`/api/marketplace/publishers/${publisher_id}`, _params ? { params: _params } : undefined)
  },

  /** List Publishers */
  async listPublishersApiMarketplacePublishersGet(_params?: any): Promise<any> {
    return http.get('/api/marketplace/publishers', _params ? { params: _params } : undefined)
  },

  /** List Local Aws Profiles */
  async listLocalAwsProfilesApiMcpAwsProfilesGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/aws/profiles', _params ? { params: _params } : undefined)
  },

  /** Draft Reply */
  async draftReplyApiMcpEmailInstanceIdDraftReplyPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/draft-reply`, data)
  },

  /** Mark Read */
  async markReadApiMcpEmailInstanceIdMarkReadPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/mark-read`, data)
  },

  /** Get Message */
  async getMessageApiMcpEmailInstanceIdMessageMessageIdGet(instance_id: any, message_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/email/${instance_id}/message/${message_id}`, _params ? { params: _params } : undefined)
  },

  /** Oauth Disconnect */
  async oauthDisconnectApiMcpEmailInstanceIdOauthDisconnectPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/oauth/disconnect`, data)
  },

  /** Oauth Start */
  async oauthStartApiMcpEmailInstanceIdOauthStartGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/email/${instance_id}/oauth/start`, _params ? { params: _params } : undefined)
  },

  /** Oauth Status */
  async oauthStatusApiMcpEmailInstanceIdOauthStatusGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/email/${instance_id}/oauth/status`, _params ? { params: _params } : undefined)
  },

  /** Send Draft */
  async sendDraftApiMcpEmailInstanceIdSendPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/send`, data)
  },

  /** Snooze Message */
  async snoozeMessageApiMcpEmailInstanceIdSnoozePost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/${instance_id}/snooze`, data)
  },

  /** List Unread */
  async listUnreadApiMcpEmailInstanceIdUnreadGet(instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/email/${instance_id}/unread`, _params ? { params: _params } : undefined)
  },

  /** Allow Sender */
  async allowSenderApiMcpEmailInstancesInstanceIdRulesAllowSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/allow_sender`, data)
  },

  /** Block Domain */
  async blockDomainApiMcpEmailInstancesInstanceIdRulesBlockDomainPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/block_domain`, data)
  },

  /** Block Sender */
  async blockSenderApiMcpEmailInstancesInstanceIdRulesBlockSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/block_sender`, data)
  },

  /** Unblock Domain */
  async unblockDomainApiMcpEmailInstancesInstanceIdRulesUnblockDomainPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/unblock_domain`, data)
  },

  /** Unblock Sender */
  async unblockSenderApiMcpEmailInstancesInstanceIdRulesUnblockSenderPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/rules/unblock_sender`, data)
  },

  /** Test Email Instance */
  async testEmailInstanceApiMcpEmailInstancesInstanceIdTestPost(instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/email/instances/${instance_id}/test`, data)
  },

  /** List Email Instances */
  async listEmailInstancesApiMcpEmailInstancesGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/email/instances', _params ? { params: _params } : undefined)
  },

  /** Create Email Instance */
  async createEmailInstanceApiMcpEmailInstancesPost(data?: any): Promise<any> {
    return http.post('/api/mcp/email/instances', data)
  },

  /** Oauth Callback */
  async oauthCallbackApiMcpEmailOauthCallbackGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/email/oauth/callback', _params ? { params: _params } : undefined)
  },

  /** Attach Mcp Package */
  async attachMcpPackageApiMcpMarketplaceAttachPost(data?: any): Promise<any> {
    return http.post('/api/mcp/marketplace/attach', data)
  },

  /** Get Mcp Catalog */
  async getMcpCatalogApiMcpMarketplaceCatalogGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/marketplace/catalog', _params ? { params: _params } : undefined)
  },

  /** Get Mcp Preview */
  async getMcpPreviewApiMcpMarketplaceGovernancePreviewPackageIdGet(package_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/marketplace/governance-preview/${package_id}`, _params ? { params: _params } : undefined)
  },

  /** Uninstall Mcp Package Canonical */
  async uninstallMcpPackageCanonicalApiMcpMarketplacePackagesPackageIdDelete(package_id: any): Promise<any> {
    return http.del(`/api/mcp/marketplace/packages/${package_id}`)
  },

  /** Get Mcp Package */
  async getMcpPackageApiMcpMarketplacePackagesPackageIdGet(package_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/marketplace/packages/${package_id}`, _params ? { params: _params } : undefined)
  },

  /** List Mcp Packages */
  async listMcpPackagesApiMcpMarketplacePackagesGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/marketplace/packages', _params ? { params: _params } : undefined)
  },

  /** Configure Mcp Server */
  async configureMcpServerApiMcpServersServerIdConfigPost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/config`, data)
  },

  /** Connect Mcp Server */
  async connectMcpServerApiMcpServersServerIdConnectPost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/connect`, data)
  },

  /** Disable Mcp Server */
  async disableMcpServerApiMcpServersServerIdDisablePost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/disable`, data)
  },

  /** Disconnect Mcp Server */
  async disconnectMcpServerApiMcpServersServerIdDisconnectPost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/disconnect`, data)
  },

  /** Enable Mcp Server */
  async enableMcpServerApiMcpServersServerIdEnablePost(server_id: any, data?: any): Promise<any> {
    return http.post(`/api/mcp/servers/${server_id}/enable`, data)
  },

  /** Preflight Mcp Server */
  async preflightMcpServerApiMcpServersServerIdPreflightGet(server_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/servers/${server_id}/preflight`, _params ? { params: _params } : undefined)
  },

  /** Get Mcp Server */
  async getMcpServerApiMcpServersServerIdGet(server_id: any, _params?: any): Promise<any> {
    return http.get(`/api/mcp/servers/${server_id}`, _params ? { params: _params } : undefined)
  },

  /** Refresh Mcp Servers */
  async refreshMcpServersApiMcpServersRefreshPost(data?: any): Promise<any> {
    return http.post('/api/mcp/servers/refresh', data)
  },

  /** List Mcp Servers */
  async listMcpServersApiMcpServersGet(_params?: any): Promise<any> {
    return http.get('/api/mcp/servers', _params ? { params: _params } : undefined)
  },

  /** Memory Entries */
  async memoryEntriesApiMemoryEntriesGet(_params?: any): Promise<any> {
    return http.get('/api/memory/entries', _params ? { params: _params } : undefined)
  },

  /** Approve Proposal */
  async approveProposalApiMemoryProposalsProposalIdApprovePost(proposal_id: any, data?: any): Promise<any> {
    return http.post(`/api/memory/proposals/${proposal_id}/approve`, data)
  },

  /** Reject Proposal */
  async rejectProposalApiMemoryProposalsProposalIdRejectPost(proposal_id: any, data?: any): Promise<any> {
    return http.post(`/api/memory/proposals/${proposal_id}/reject`, data)
  },

  /** Get Proposal */
  async getProposalApiMemoryProposalsProposalIdGet(proposal_id: any, _params?: any): Promise<any> {
    return http.get(`/api/memory/proposals/${proposal_id}`, _params ? { params: _params } : undefined)
  },

  /** Proposal Stats */
  async proposalStatsApiMemoryProposalsStatsGet(_params?: any): Promise<any> {
    return http.get('/api/memory/proposals/stats', _params ? { params: _params } : undefined)
  },

  /** List Proposals */
  async listProposalsApiMemoryProposalsGet(_params?: any): Promise<any> {
    return http.get('/api/memory/proposals', _params ? { params: _params } : undefined)
  },

  /** Propose Memory */
  async proposeMemoryApiMemoryProposePost(data?: any): Promise<any> {
    return http.post('/api/memory/propose', data)
  },

  /** List Messages */
  async listMessagesApiMessagesGet(_params?: any): Promise<any> {
    return http.get('/api/messages', _params ? { params: _params } : undefined)
  },

  /** Mobile Chat */
  async mobileChatApiMobileChatPost(data?: any): Promise<any> {
    return http.post('/api/mobile/chat', data)
  },

  /** Clear Alerts */
  async clearAlertsApiModeAlertsClearPost(data?: any): Promise<any> {
    return http.post('/api/mode/alerts/clear', data)
  },

  /** List Alerts */
  async listAlertsApiModeAlertsGet(_params?: any): Promise<any> {
    return http.get('/api/mode/alerts', _params ? { params: _params } : undefined)
  },

  /** Get Stats */
  async getStatsApiModeStatsGet(_params?: any): Promise<any> {
    return http.get('/api/mode/stats', _params ? { params: _params } : undefined)
  },

  /** Delete Model */
  async deleteModelApiModelsModelIdDelete(model_id: any): Promise<any> {
    return http.del(`/api/models/${model_id}`)
  },

  /** List Models */
  async listModelsApiModelsListGet(_params?: any): Promise<any> {
    return http.get('/api/models/list', _params ? { params: _params } : undefined)
  },

  /** Pull Model Progress */
  async pullModelProgressApiModelsPullTaskIdProgressGet(task_id: any, _params?: any): Promise<any> {
    return http.get(`/api/models/pull/${task_id}/progress`, _params ? { params: _params } : undefined)
  },

  /** Pull Model */
  async pullModelApiModelsPullPost(data?: any): Promise<any> {
    return http.post('/api/models/pull', data)
  },

  /** Approve Request */
  async approveRequestApiNetworkCapabilitiesRequestIdApprovePost(request_id: any, data?: any): Promise<any> {
    return http.post(`/api/network/capabilities/${request_id}/approve`, data)
  },

  /** Revoke Request */
  async revokeRequestApiNetworkCapabilitiesRequestIdRevokePost(request_id: any, data?: any): Promise<any> {
    return http.post(`/api/network/capabilities/${request_id}/revoke`, data)
  },

  /** Request Capability */
  async requestCapabilityApiNetworkCapabilitiesRequestPost(data?: any): Promise<any> {
    return http.post('/api/network/capabilities/request', data)
  },

  /** Capabilities Status */
  async capabilitiesStatusApiNetworkCapabilitiesStatusGet(_params?: any): Promise<any> {
    return http.get('/api/network/capabilities/status', _params ? { params: _params } : undefined)
  },

  /** Provision Cloudflare Access */
  async provisionCloudflareAccessApiNetworkCloudflareAccessProvisionPost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/access/provision', data)
  },

  /** Revoke Cloudflare Access */
  async revokeCloudflareAccessApiNetworkCloudflareAccessRevokePost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/access/revoke', data)
  },

  /** Cloudflare Access Status */
  async cloudflareAccessStatusApiNetworkCloudflareAccessStatusGet(_params?: any): Promise<any> {
    return http.get('/api/network/cloudflare/access/status', _params ? { params: _params } : undefined)
  },

  /** Cloudflare Daemon Disable Autostart */
  async cloudflareDaemonDisableAutostartApiNetworkCloudflareDaemonAutostartDisablePost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/daemon/autostart/disable', data)
  },

  /** Cloudflare Daemon Enable Autostart */
  async cloudflareDaemonEnableAutostartApiNetworkCloudflareDaemonAutostartEnablePost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/daemon/autostart/enable', data)
  },

  /** Cloudflare Daemon Install */
  async cloudflareDaemonInstallApiNetworkCloudflareDaemonInstallPost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/daemon/install', data)
  },

  /** Cloudflare Daemon Restart */
  async cloudflareDaemonRestartApiNetworkCloudflareDaemonRestartPost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/daemon/restart', data)
  },

  /** Cloudflare Daemon Start */
  async cloudflareDaemonStartApiNetworkCloudflareDaemonStartPost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/daemon/start', data)
  },

  /** Cloudflare Daemon Status */
  async cloudflareDaemonStatusApiNetworkCloudflareDaemonStatusGet(_params?: any): Promise<any> {
    return http.get('/api/network/cloudflare/daemon/status', _params ? { params: _params } : undefined)
  },

  /** Cloudflare Daemon Stop */
  async cloudflareDaemonStopApiNetworkCloudflareDaemonStopPost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/daemon/stop', data)
  },

  /** Cloudflare Daemon Uninstall */
  async cloudflareDaemonUninstallApiNetworkCloudflareDaemonUninstallPost(data?: any): Promise<any> {
    return http.post('/api/network/cloudflare/daemon/uninstall', data)
  },

  /** Get Network Config */
  async getNetworkConfigApiNetworkConfigGet(_params?: any): Promise<any> {
    return http.get('/api/network/config', _params ? { params: _params } : undefined)
  },

  /** Set Network Config */
  async setNetworkConfigApiNetworkConfigPost(data?: any): Promise<any> {
    return http.post('/api/network/config', data)
  },

  /** Get Overview */
  async getOverviewApiOverviewGet(_params?: any): Promise<any> {
    return http.get('/api/overview', _params ? { params: _params } : undefined)
  },

  /** List Plugins */
  async listPluginsApiPluginsGet(_params?: any): Promise<any> {
    return http.get('/api/plugins', _params ? { params: _params } : undefined)
  },

  /** Get Preview Content */
  async getPreviewContentApiPreviewPreviewIdContentGet(preview_id: any, _params?: any): Promise<any> {
    return http.get(`/api/preview/${preview_id}/content`, _params ? { params: _params } : undefined)
  },

  /** Reload Preview */
  async reloadPreviewApiPreviewPreviewIdReloadPost(preview_id: any, data?: any): Promise<any> {
    return http.post(`/api/preview/${preview_id}/reload`, data)
  },

  /** Remove Preview */
  async removePreviewApiPreviewPreviewIdDelete(preview_id: any): Promise<any> {
    return http.del(`/api/preview/${preview_id}`)
  },

  /** Get Preview */
  async getPreviewApiPreviewPreviewIdGet(preview_id: any, _params?: any): Promise<any> {
    return http.get(`/api/preview/${preview_id}`, _params ? { params: _params } : undefined)
  },

  /** Create Preview */
  async createPreviewApiPreviewPost(data?: any): Promise<any> {
    return http.post('/api/preview', data)
  },

  /** Archive Project */
  async archiveProjectApiProjectsProjectIdArchivePost(project_id: any, data?: any): Promise<any> {
    return http.post(`/api/projects/${project_id}/archive`, data)
  },

  /** Delete Repo */
  async deleteRepoApiProjectsProjectIdReposRepoIdDelete(project_id: any, repo_id: any): Promise<any> {
    return http.del(`/api/projects/${project_id}/repos/${repo_id}`)
  },

  /** Get Repo */
  async getRepoApiProjectsProjectIdReposRepoIdGet(project_id: any, repo_id: any, _params?: any): Promise<any> {
    return http.get(`/api/projects/${project_id}/repos/${repo_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Repo */
  async updateRepoApiProjectsProjectIdReposRepoIdPut(project_id: any, repo_id: any, data?: any): Promise<any> {
    return http.put(`/api/projects/${project_id}/repos/${repo_id}`, data)
  },

  /** List Repos */
  async listReposApiProjectsProjectIdReposGet(project_id: any, _params?: any): Promise<any> {
    return http.get(`/api/projects/${project_id}/repos`, _params ? { params: _params } : undefined)
  },

  /** Add Repo */
  async addRepoApiProjectsProjectIdReposPost(project_id: any, data?: any): Promise<any> {
    return http.post(`/api/projects/${project_id}/repos`, data)
  },

  /** Delete Project */
  async deleteProjectApiProjectsProjectIdDelete(project_id: any): Promise<any> {
    return http.del(`/api/projects/${project_id}`)
  },

  /** Get Project Detail */
  async getProjectDetailApiProjectsProjectIdGet(project_id: any, _params?: any): Promise<any> {
    return http.get(`/api/projects/${project_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Project */
  async updateProjectApiProjectsProjectIdPatch(project_id: any, data?: any): Promise<any> {
    return http.patch(`/api/projects/${project_id}`, data)
  },

  /** List Projects */
  async listProjectsApiProjectsGet(_params?: any): Promise<any> {
    return http.get('/api/projects', _params ? { params: _params } : undefined)
  },

  /** Create Project */
  async createProjectApiProjectsPost(data?: any): Promise<any> {
    return http.post('/api/projects', data)
  },

  /** Detect Executable */
  async detectExecutableApiProvidersProviderIdExecutableDetectGet(provider_id: any, _params?: any): Promise<any> {
    return http.get(`/api/providers/${provider_id}/executable/detect`, _params ? { params: _params } : undefined)
  },

  /** Validate Executable */
  async validateExecutableApiProvidersProviderIdExecutableValidatePost(provider_id: any, data?: any): Promise<any> {
    return http.post(`/api/providers/${provider_id}/executable/validate`, data)
  },

  /** Set Executable */
  async setExecutableApiProvidersProviderIdExecutablePut(provider_id: any, data?: any): Promise<any> {
    return http.put(`/api/providers/${provider_id}/executable`, data)
  },

  /** Restart Instance */
  async restartInstanceApiProvidersProviderIdInstancesInstanceIdRestartPost(provider_id: any, instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/providers/${provider_id}/instances/${instance_id}/restart`, data)
  },

  /** Start Instance */
  async startInstanceApiProvidersProviderIdInstancesInstanceIdStartPost(provider_id: any, instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/providers/${provider_id}/instances/${instance_id}/start`, data)
  },

  /** Instance Status */
  async instanceStatusApiProvidersProviderIdInstancesInstanceIdStatusGet(provider_id: any, instance_id: any, _params?: any): Promise<any> {
    return http.get(`/api/providers/${provider_id}/instances/${instance_id}/status`, _params ? { params: _params } : undefined)
  },

  /** Stop Instance */
  async stopInstanceApiProvidersProviderIdInstancesInstanceIdStopPost(provider_id: any, instance_id: any, data?: any): Promise<any> {
    return http.post(`/api/providers/${provider_id}/instances/${instance_id}/stop`, data)
  },

  /** Delete Instance */
  async deleteInstanceApiProvidersProviderIdInstancesInstanceIdDelete(provider_id: any, instance_id: any): Promise<any> {
    return http.del(`/api/providers/${provider_id}/instances/${instance_id}`)
  },

  /** List Instances */
  async listInstancesApiProvidersProviderIdInstancesGet(provider_id: any, _params?: any): Promise<any> {
    return http.get(`/api/providers/${provider_id}/instances`, _params ? { params: _params } : undefined)
  },

  /** Add Instance */
  async addInstanceApiProvidersProviderIdInstancesPost(provider_id: any, data?: any): Promise<any> {
    return http.post(`/api/providers/${provider_id}/instances`, data)
  },

  /** List Provider Models */
  async listProviderModelsApiProvidersProviderIdModelsGet(provider_id: any, _params?: any): Promise<any> {
    return http.get(`/api/providers/${provider_id}/models`, _params ? { params: _params } : undefined)
  },

  /** Detect Models Directories */
  async detectModelsDirectoriesApiProvidersModelsDirectoriesDetectGet(_params?: any): Promise<any> {
    return http.get('/api/providers/models/directories/detect', _params ? { params: _params } : undefined)
  },

  /** Get Models Directories */
  async getModelsDirectoriesApiProvidersModelsDirectoriesGet(_params?: any): Promise<any> {
    return http.get('/api/providers/models/directories', _params ? { params: _params } : undefined)
  },

  /** Set Models Directory */
  async setModelsDirectoryApiProvidersModelsDirectoriesPut(data?: any): Promise<any> {
    return http.put('/api/providers/models/directories', data)
  },

  /** List Models Files */
  async listModelsFilesApiProvidersModelsFilesGet(_params?: any): Promise<any> {
    return http.get('/api/providers/models/files', _params ? { params: _params } : undefined)
  },

  /** Refresh Providers Status */
  async refreshProvidersStatusApiProvidersRefreshPost(data?: any): Promise<any> {
    return http.post('/api/providers/refresh', data)
  },

  /** List Providers */
  async listProvidersApiProvidersGet(_params?: any): Promise<any> {
    return http.get('/api/providers', _params ? { params: _params } : undefined)
  },

  /** Execute Remote Connection */
  async executeRemoteConnectionApiRemoteConnectionsConnectionIdExecutePost(connection_id: any, data?: any): Promise<any> {
    return http.post(`/api/remote/connections/${connection_id}/execute`, data)
  },

  /** Delete Remote Connection */
  async deleteRemoteConnectionApiRemoteConnectionsConnectionIdDelete(connection_id: any): Promise<any> {
    return http.del(`/api/remote/connections/${connection_id}`)
  },

  /** Get Remote Connection */
  async getRemoteConnectionApiRemoteConnectionsConnectionIdGet(connection_id: any, _params?: any): Promise<any> {
    return http.get(`/api/remote/connections/${connection_id}`, _params ? { params: _params } : undefined)
  },

  /** List Remote Connections */
  async listRemoteConnectionsApiRemoteConnectionsGet(_params?: any): Promise<any> {
    return http.get('/api/remote/connections', _params ? { params: _params } : undefined)
  },

  /** Delete Repo */
  async deleteRepoApiReposRepoIdDelete(repo_id: any): Promise<any> {
    return http.del(`/api/repos/${repo_id}`)
  },

  /** Get Repo */
  async getRepoApiReposRepoIdGet(repo_id: any, _params?: any): Promise<any> {
    return http.get(`/api/repos/${repo_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Repo */
  async updateRepoApiReposRepoIdPatch(repo_id: any, data?: any): Promise<any> {
    return http.patch(`/api/repos/${repo_id}`, data)
  },

  /** List Repos */
  async listReposApiReposGet(_params?: any): Promise<any> {
    return http.get('/api/repos', _params ? { params: _params } : undefined)
  },

  /** Create Repo */
  async createRepoApiReposPost(data?: any): Promise<any> {
    return http.post('/api/repos', data)
  },

  /** Risk Timeline */
  async riskTimelineApiRiskTimelineGet(_params?: any): Promise<any> {
    return http.get('/api/risk/timeline', _params ? { params: _params } : undefined)
  },

  /** Fix Permissions */
  async fixPermissionsApiRuntimeFixPermissionsPost(data?: any): Promise<any> {
    return http.post('/api/runtime/fix-permissions', data)
  },

  /** Run Selfcheck */
  async runSelfcheckApiSelfcheckPost(data?: any): Promise<any> {
    return http.post('/api/selfcheck', data)
  },

  /** Delete Message */
  async deleteMessageApiSessionsSessionIdMessagesMessageIdDelete(session_id: any, message_id: any): Promise<any> {
    return http.del(`/api/sessions/${session_id}/messages/${message_id}`)
  },

  /** List Messages */
  async listMessagesApiSessionsSessionIdMessagesGet(session_id: any, _params?: any): Promise<any> {
    return http.get(`/api/sessions/${session_id}/messages`, _params ? { params: _params } : undefined)
  },

  /** Add Message */
  async addMessageApiSessionsSessionIdMessagesPost(session_id: any, data?: any): Promise<any> {
    return http.post(`/api/sessions/${session_id}/messages`, data)
  },

  /** Touch Session Presence */
  async touchSessionPresenceApiSessionsSessionIdPresenceTouchPost(session_id: any, data?: any): Promise<any> {
    return http.post(`/api/sessions/${session_id}/presence/touch`, data)
  },

  /** Delete Session */
  async deleteSessionApiSessionsSessionIdDelete(session_id: any): Promise<any> {
    return http.del(`/api/sessions/${session_id}`)
  },

  /** Get Session */
  async getSessionApiSessionsSessionIdGet(session_id: any, _params?: any): Promise<any> {
    return http.get(`/api/sessions/${session_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Session */
  async updateSessionApiSessionsSessionIdPut(session_id: any, data?: any): Promise<any> {
    return http.put(`/api/sessions/${session_id}`, data)
  },

  /** Delete All Sessions */
  async deleteAllSessionsApiSessionsDelete(): Promise<any> {
    return http.del('/api/sessions')
  },

  /** List Sessions */
  async listSessionsApiSessionsGet(_params?: any): Promise<any> {
    return http.get('/api/sessions', _params ? { params: _params } : undefined)
  },

  /** Create Session */
  async createSessionApiSessionsPost(data?: any): Promise<any> {
    return http.post('/api/sessions', data)
  },

  /** Get Skill */
  async getSkillApiSkillsSkillIdGet(skill_id: any, _params?: any): Promise<any> {
    return http.get(`/api/skills/${skill_id}`, _params ? { params: _params } : undefined)
  },

  /** Install Skill */
  async installSkillApiSkillsInstallPost(data?: any): Promise<any> {
    return http.post('/api/skills/install', data)
  },

  /** List Skills */
  async listSkillsApiSkillsGet(_params?: any): Promise<any> {
    return http.get('/api/skills', _params ? { params: _params } : undefined)
  },

  /** Delete Snippet */
  async deleteSnippetApiSnippetsSnippetIdDelete(snippet_id: any): Promise<any> {
    return http.del(`/api/snippets/${snippet_id}`)
  },

  /** Update Snippet */
  async updateSnippetApiSnippetsSnippetIdPut(snippet_id: any, data?: any): Promise<any> {
    return http.put(`/api/snippets/${snippet_id}`, data)
  },

  /** List Snippets */
  async listSnippetsApiSnippetsGet(_params?: any): Promise<any> {
    return http.get('/api/snippets', _params ? { params: _params } : undefined)
  },

  /** Create Snippet */
  async createSnippetApiSnippetsPost(data?: any): Promise<any> {
    return http.post('/api/snippets', data)
  },

  /** Desktop Status */
  async desktopStatusApiStatusGet(_params?: any): Promise<any> {
    return http.get('/api/status', _params ? { params: _params } : undefined)
  },

  /** Get Stream Events */
  async getStreamEventsApiStreamsSessionIdRunIdGet(session_id: any, run_id: any, _params?: any): Promise<any> {
    return http.get(`/api/streams/${session_id}/${run_id}`, _params ? { params: _params } : undefined)
  },

  /** Get Latest Stream Run */
  async getLatestStreamRunApiStreamsSessionIdLatestRunGet(session_id: any, _params?: any): Promise<any> {
    return http.get(`/api/streams/${session_id}/latest-run`, _params ? { params: _params } : undefined)
  },

  /** Get Task Route */
  async getTaskRouteApiTasksTaskIdRouteGet(task_id: any, _params?: any): Promise<any> {
    return http.get(`/api/tasks/${task_id}/route`, _params ? { params: _params } : undefined)
  },

  /** Update Task Route */
  async updateTaskRouteApiTasksTaskIdRoutePost(task_id: any, data?: any): Promise<any> {
    return http.post(`/api/tasks/${task_id}/route`, data)
  },

  /** Delete Task */
  async deleteTaskApiTasksTaskIdDelete(task_id: any): Promise<any> {
    return http.del(`/api/tasks/${task_id}`)
  },

  /** Get Task */
  async getTaskApiTasksTaskIdGet(task_id: any, _params?: any): Promise<any> {
    return http.get(`/api/tasks/${task_id}`, _params ? { params: _params } : undefined)
  },

  /** Batch Create Tasks */
  async batchCreateTasksApiTasksBatchPost(data?: any): Promise<any> {
    return http.post('/api/tasks/batch', data)
  },

  /** Create And Start Task */
  async createAndStartTaskApiTasksCreateAndStartPost(data?: any): Promise<any> {
    return http.post('/api/tasks/create_and_start', data)
  },

  /** Cancel Exec Task */
  async cancelExecTaskApiTasksItemsTaskIdCancelPost(task_id: any, data?: any): Promise<any> {
    return http.post(`/api/tasks/items/${task_id}/cancel`, data)
  },

  /** Retry Exec Task */
  async retryExecTaskApiTasksItemsTaskIdRetryPost(task_id: any, data?: any): Promise<any> {
    return http.post(`/api/tasks/items/${task_id}/retry`, data)
  },

  /** Get Exec Task */
  async getExecTaskApiTasksItemsTaskIdGet(task_id: any, _params?: any): Promise<any> {
    return http.get(`/api/tasks/items/${task_id}`, _params ? { params: _params } : undefined)
  },

  /** List Exec Tasks */
  async listExecTasksApiTasksItemsGet(_params?: any): Promise<any> {
    return http.get('/api/tasks/items', _params ? { params: _params } : undefined)
  },

  /** List Tasks */
  async listTasksApiTasksGet(_params?: any): Promise<any> {
    return http.get('/api/tasks', _params ? { params: _params } : undefined)
  },

  /** Create Task */
  async createTaskApiTasksPost(data?: any): Promise<any> {
    return http.post('/api/tasks', data)
  },

  /** List Tools */
  async listToolsApiToolsGet(_params?: any): Promise<any> {
    return http.get('/api/tools', _params ? { params: _params } : undefined)
  },

  /** Export Transparency Bundle */
  async exportTransparencyBundleApiTransparencyExportGet(_params?: any): Promise<any> {
    return http.get('/api/transparency/export', _params ? { params: _params } : undefined)
  },

  /** List Triggers */
  async listTriggersApiTriggersGet(_params?: any): Promise<any> {
    return http.get('/api/triggers', _params ? { params: _params } : undefined)
  },

  /** Trust Trajectory */
  async trustTrajectoryApiTrustTrajectorySubjectIdGet(subject_id: any, _params?: any): Promise<any> {
    return http.get(`/api/trust/trajectory/${subject_id}`, _params ? { params: _params } : undefined)
  },

  /** List Users */
  async listUsersApiUsersGet(_params?: any): Promise<any> {
    return http.get('/api/users', _params ? { params: _params } : undefined)
  },

  /** List Project Repos */
  async listProjectReposApiV031ProjectsProjectIdReposGet(project_id: any, _params?: any): Promise<any> {
    return http.get(`/api/v0.31/projects/${project_id}/repos`, _params ? { params: _params } : undefined)
  },

  /** Create Project Repo */
  async createProjectRepoApiV031ProjectsProjectIdReposPost(project_id: any, data?: any): Promise<any> {
    return http.post(`/api/v0.31/projects/${project_id}/repos`, data)
  },

  /** Get Project */
  async getProjectApiV031ProjectsProjectIdGet(project_id: any, _params?: any): Promise<any> {
    return http.get(`/api/v0.31/projects/${project_id}`, _params ? { params: _params } : undefined)
  },

  /** List Projects */
  async listProjectsApiV031ProjectsGet(_params?: any): Promise<any> {
    return http.get('/api/v0.31/projects', _params ? { params: _params } : undefined)
  },

  /** Create Project */
  async createProjectApiV031ProjectsPost(data?: any): Promise<any> {
    return http.post('/api/v0.31/projects', data)
  },

  /** List Tasks */
  async listTasksApiV031TasksGet(_params?: any): Promise<any> {
    return http.get('/api/v0.31/tasks', _params ? { params: _params } : undefined)
  },

  /** Create Task */
  async createTaskApiV031TasksPost(data?: any): Promise<any> {
    return http.post('/api/v0.31/tasks', data)
  },

  /** Approve Review Queue */
  async approveReviewQueueApiV3ReviewQueueItemIdApprovePost(item_id: any, data?: any): Promise<any> {
    return http.post(`/api/v3/review-queue/${item_id}/approve`, data)
  },

  /** Reject Review Queue */
  async rejectReviewQueueApiV3ReviewQueueItemIdRejectPost(item_id: any, data?: any): Promise<any> {
    return http.post(`/api/v3/review-queue/${item_id}/reject`, data)
  },

  /** Get Review Queue Item */
  async getReviewQueueItemApiV3ReviewQueueItemIdGet(item_id: any, _params?: any): Promise<any> {
    return http.get(`/api/v3/review-queue/${item_id}`, _params ? { params: _params } : undefined)
  },

  /** List Review Queue */
  async listReviewQueueApiV3ReviewQueueGet(_params?: any): Promise<any> {
    return http.get('/api/v3/review-queue', _params ? { params: _params } : undefined)
  },

  /** Delete Voice Contact */
  async deleteVoiceContactApiVoiceContactsContactIdDelete(contact_id: any): Promise<any> {
    return http.del(`/api/voice-contacts/${contact_id}`)
  },

  /** Update Voice Contact */
  async updateVoiceContactApiVoiceContactsContactIdPut(contact_id: any, data?: any): Promise<any> {
    return http.put(`/api/voice-contacts/${contact_id}`, data)
  },

  /** List Voice Contacts */
  async listVoiceContactsApiVoiceContactsGet(_params?: any): Promise<any> {
    return http.get('/api/voice-contacts', _params ? { params: _params } : undefined)
  },

  /** Create Voice Contact */
  async createVoiceContactApiVoiceContactsPost(data?: any): Promise<any> {
    return http.post('/api/voice-contacts', data)
  },

  /** Health */
  async healthApiVoiceHealthGet(_params?: any): Promise<any> {
    return http.get('/api/voice/health', _params ? { params: _params } : undefined)
  },

  /** Inbound */
  async inboundApiVoiceTwilioInboundPost(data?: any): Promise<any> {
    return http.post('/api/voice/twilio/inbound', data)
  },

  /** Cancel Work Item */
  async cancelWorkItemApiWorkItemsWorkIdCancelPost(work_id: any, data?: any): Promise<any> {
    return http.post(`/api/work/items/${work_id}/cancel`, data)
  },

  /** Get Work Item */
  async getWorkItemApiWorkItemsWorkIdGet(work_id: any, _params?: any): Promise<any> {
    return http.get(`/api/work/items/${work_id}`, _params ? { params: _params } : undefined)
  },

  /** List Work Items */
  async listWorkItemsApiWorkItemsGet(_params?: any): Promise<any> {
    return http.get('/api/work/items', _params ? { params: _params } : undefined)
  },

  /** Get Work Session */
  async getWorkSessionApiWorkSessionsSessionIdGet(session_id: any, _params?: any): Promise<any> {
    return http.get(`/api/work/sessions/${session_id}`, _params ? { params: _params } : undefined)
  },

  /** Update Work Session */
  async updateWorkSessionApiWorkSessionsSessionIdPut(session_id: any, data?: any): Promise<any> {
    return http.put(`/api/work/sessions/${session_id}`, data)
  },

  /** List Work Sessions */
  async listWorkSessionsApiWorkSessionsGet(_params?: any): Promise<any> {
    return http.get('/api/work/sessions', _params ? { params: _params } : undefined)
  },

  /** Create Work Session */
  async createWorkSessionApiWorkSessionsPost(data?: any): Promise<any> {
    return http.post('/api/work/sessions', data)
  }
}

export type systemServiceGenApi = typeof systemServiceGen
