from __future__ import annotations

from typing import Any, Dict, List, Protocol, Tuple


class PlatformActions(Protocol):
    def whoami(self) -> Dict[str, Any]: ...
    def check_permissions(self, actions: List[str]) -> Dict[str, Any]: ...
    def resolve_resource(self, kind: str, resource_id: str, region: str | None) -> Dict[str, Any]: ...
    def list_metrics(self, query: Dict[str, Any]) -> List[Dict[str, Any]]: ...
    def get_metric_data(self, req: Dict[str, Any]) -> Dict[str, Any]: ...
    def managed_node_status(self, resource: Dict[str, Any]) -> Dict[str, Any]: ...
    def run_managed_command(self, resource: Dict[str, Any], command: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_compute_identity_binding(self, resource: Dict[str, Any]) -> Dict[str, Any]: ...
    def bind_compute_identity(self, resource: Dict[str, Any], binding: Dict[str, Any]) -> Dict[str, Any]: ...
    def create_minimal_compute_identity(self, spec: Dict[str, Any]) -> Dict[str, Any]: ...
    def list_inventory(self, scope: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_billing_summary(self, window: Dict[str, Any]) -> Dict[str, Any]: ...
    def get_org_structure(self) -> Dict[str, Any]: ...
